### ISSUE TITLE
firehose agent VS fluent-bit with firehose plugin

### ISSUE THREAD

**Issue by yanivpaz** [aws/aws-for-fluent-bit#104]
What is the recommended method to deliver logs to firehose ?
[firehose agent](https://docs.aws.amazon.com/firehose/latest/dev/writing-with-agents.html ) or filebeat with firehose plugin?
is there any comparison of performance?

PS
I am following the great guideline mentioned [here](https://youtu.be/8jwvg3vgdZk?t=1465 )

**Comment by PettitWesley** [comment]
Hey @yanivpaz as far as I know AWS does not have an official recommendation on Kinesis Agent vs Fluent Bit.

As a Fluent Bit maintainer, I recommend Fluent Bit with the new core high performance Kinesis Firehose output: https://docs.fluentbit.io/manual/pipeline/outputs/firehose

My recommendation is based on the following reasons:
1. IIRC Kinesis Agent is written in Java and has fairly high memory usage (I played with it once 2 years ago, before I got into Fluent Bit). You can see some benchmarks for Fluent Bit here, comparing it with highly optimized agents that are written in Golang- the new kinesis_firehose output should be similar to the Fluent Bit C CW output: https://docs.google.com/document/d/1Tlg06YVpkDvwoN_1YvpxyHEv75aosX6RfxmvKK2j0SY/edit#
2. Fluent Bit has more features for ingesting, processing, parsing, and manipulating records prior to sending them to Firehose.

I'll check with some folks internally to see if we can publish clear guidance that Fluent Bit is probably preferable for logging use cases.

**Comment by yanivpaz** [comment]
Thanks a lot for the fast answer!

I want to send the logs to AWS elasticsearch .
 
I saw [here](https://docs.aws.amazon.com/firehose/latest/dev/limits.html) the numbers for firehose : 5,000 records/second, 2,000 requests/second, and 5 MiB/second.

do you know if there are best practices when I can  skip firehose and send the logs directly to elastic search ?

**Comment by PettitWesley** [comment]
So first of all, note that you can submit a limit increase and get higher limits for your firehose stream if needed.

Fluent Bit can send directly to Amazon ElasticSearch Service: https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch

Whether or not sending directly is a best practice depends on factors like:
1. What is your total rate of ingestion to the cluster
2. How much Fluent Bit can buffer
3. How tolerant you are of dataloss

Apparently ES is not reliable at ingestion data at high throughputs. Also, if your cluster experiences any issue, you could have a brief outage for ingestion. 

With Firehose, you have a distributed buffer in the cloud that can backoff, retry, and buffer data for up to 24 hours. Fluent Bit can also buffer, retry, and backoff, but in general you should trust Firehose more. I can't give exact numbers or guidance on what the cutoff is for one of the other approach being preferable.

But consider the following clear scenarios:
1. Sending direct to AES is safe enough: Your data ingestion rate is reasonable for your cluster size, and it is not expected to spike. Fluent bit is configured with a persistent file buffer, so buffering is safe. And you are okay with a small risk of data loss.
2. Firehose is best: Your data ingestion rate is very high or it may spike suddenly. Fluent Bit has not persistent disk buffer, only memory buffer, and your are not willing to tolerate any risk of data loss.

Hopefully that helps.

**Comment by axot** [comment]
Hi,

Just curious what is the buffer size and refresh interval if using fluent-bit with firehose plugin,
I can't find related config in the [document](https://docs.fluentbit.io/manual/pipeline/outputs/firehose).
Want to know if host error happens on an instance how much data will be lost.

**Comment by PettitWesley** [comment]
@axot In Fluent Bit, flushing and buffering are controlled by system level settings, not in the plugin itself: https://docs.fluentbit.io/manual/concepts/buffering

**Comment by sparrc** [comment]
I dont see any further actions to take on this ticket, please feel free to reopen or open a new ticket if further information is needed
