### ISSUE TITLE
Docker CIS benchmark compliance for fluent-bit image

### ISSUE THREAD

**Issue by infa-ssaurabh** [aws/aws-for-fluent-bit#105]
Can we make aws-for-fluent-bit image to be compliance with Docker CIS benchmark?

After scan, we get below compliance issue:
`WARN	- CIS-DI-0001: Create a user for the container`

**Comment by PettitWesley** [comment]
@infa-ssaurabh I am not familiar with Docker CIS... is that flagging the fact that Fluent Bit runs as root/PID 0? Or is it just that we need to run it as named user but it can be PID 0?

In ECS FireLens fluent bit has to run as PID 0 in the container for things to work.

**Comment by zhonghui12** [comment]
Close this issue for no response. Please re-open it if you have more problems.
