### ISSUE TITLE
Update Fluentbit to 1.6.6?

### ISSUE THREAD

**Issue by diranged** [aws/aws-for-fluent-bit#106]
https://github.com/fluent/fluent-bit/pull/2782

Can we get fluentbit updated to 1.6.6 with the S3 Canned ACL support?

**Comment by diranged** [comment]
@PettitWesley Hey.. can we get an updated release sometime soon?

**Comment by PettitWesley** [comment]
Yeah we'll try to do one sometime this week

**Comment by zhonghui12** [comment]
We have updated Fluent Bit to 1.6.8 in recent release: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.10.0.

Will close this issue. Thanks.
