### ISSUE TITLE
Does CloudWatch plugin support proxy?

### ISSUE THREAD

**Issue by pranavmarla** [aws/aws-for-fluent-bit#107]
**Bug Description**
I'm trying to send a log from EKS to CloudWatch using Amazon's [CloudWatch output plugin](https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit) -- unfortunately, Fluent Bit appears to fail at the first step (retrieving the required IAM credentials and assuming the required IAM role) because it cannot access _sts.amazonaws.com_ without a proxy:
```
time="2020-11-25T21:51:32Z" level=error msg="WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: dial tcp XXX:443: i/o timeout"
```
So, is there a way to specify a proxy in the CloudWatch plugin config, **that will only apply to that plugin**?

ps: I know that, in [v1.6.4](https://fluentbit.io/announcements/v1.6.4/) of Fluent Bit, support for a global HTTP_PROXY env var was introduced -- unfortunately, as I explain [here](https://github.com/fluent/fluent-bit/issues/2805), due to its lack of support for an accompanying NO_PROXY env var, that doesn't solve my problem either. So, ideally, I need some proxy config that will only apply to this CloudWatch output plugin.

**Config**
Here's my Fluent Bit config for CloudWatch:
```
[OUTPUT]
    Name              cloudwatch
    Match             *
    region            us-east-1
    log_group_name    test-group
    log_stream_name   $(tag)
    auto_create_group true
```

**Environment**
- AWS Fluent Bit Docker Image Version: `2.9.0`
- Fluent Bit: `1.6.3`
- Kubernetes (EKS)

**Comment by PettitWesley** [comment]
> ps: I know that, in v1.6.4 of Fluent Bit, support for a global HTTP_PROXY env var was introduced 

That actually isn't relevant for the `cloudwatch` plugin. Its a separate binary that uses the AWS SDK Go to make and send requests.

The question is whether the SDK Go supports those standard proxy env vars or not... I am pretty sure it should

**Comment by PettitWesley** [comment]
Docs suggest it is supported: https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html

I remember a while ago I talked to a customer who was using the Firehose go plugin with an http proxy as well, and it worked.

Can you double check everything and also give us your actual error output and settings? This should work.

**Comment by pranavmarla** [comment]
Hi @PettitWesley , thanks for clearing that up! It looks like my initial testing may have been affected by Amazon's us-east-1 outage at the time. I have since redone my testing, and this is what I found:

Using v2.9.0 of Amazon's custom Fluent Bit image (containing v1.6.3 of Fluent Bit):

1. Using uppercase environment variables (HTTP_PROXY, HTTPS_PROXY, NO_PROXY):
Calls to STS+CloudWatch work, without breaking calls to Kubernetes API

2. Using lowercase environment variables (http_proxy, https_proxy, no_proxy):
Calls to STS+CloudWatch work, without breaking calls to Kubernetes API

So, at this point, since Amazon's CloudWatch plugin is the only thing that is affected by either the uppercase or lowercase environment variables, I can use either option without breaking the rest of Fluent Bit (specifically, the Kubernetes metadata filter's calls to the Kubernetes API server).

**However, what I'm concerned about, and still need to test, is what happens when a future version of Amazon's custom Fluent Bit image is released containing Fluent Bit of version >= 1.6.4**. 
As far as I understand, starting from that version of Fluent Bit, the uppercase environment variable HTTP_PROXY (but literally no other proxy environment variable) is supported, and thus affects all of Fluent Bit (including the Kubernetes metadata filter) without exception -- i.e. NO_PROXY is not supported!
In that scenario, I suspect only option #2 (using lowercase environment variables) would give me the effect that I want -- i.e. proxies only affect Amazon's custom CloudWatch plugin, but not the built-in Kubernetes metadata filter.

**Do you have any idea when the next version of Amazon's custom Fluent Bit Docker image, containing Fluent Bit >= v1.6.4, will be released, so I can validate my theory?**

**Comment by PettitWesley** [comment]
@pranavmarla The next release should be some time in the next two weeks.

However, you can very easily build a custom version of this image with Fluent Bit 1.6.4 to test this out. Simply clone this repo and update the Dockerfile to pull 1.6.4: https://github.com/aws/aws-for-fluent-bit/blob/mainline/Dockerfile#L4

**Comment by pranavmarla** [comment]
Great, thank you!

**Comment by zhonghui12** [comment]
Hi @pranavmarla ,

We have upgraded Fluent Bit to 1.6.8 in recent release: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.10.0. 

Will close this issue. Please reopen it if you have any questions about it. Thanks.
