### ISSUE TITLE
HTTP basic authentication support for AWS Elastic

### ISSUE THREAD

**Issue by yanivpaz** [aws/aws-for-fluent-bit#108]
AWS Elastic supports two access controls:
- IAM ARN as a master user
- HTTP basic authentication - master user/pass

Does HTTP basic authentication is supported in this plugin?
I don't see it :
https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/values.yaml#L96

**Comment by yanivpaz** [comment]
I see that it's supported in fluentd :
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch.yaml#L43

**Comment by PettitWesley** [comment]
https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch

Basic HTTP Auth is supported with `HTTP_User` and `HTTP_Password`

AWS of course strongly recommends that you use IAM auth...

**Comment by zhonghui12** [comment]
Hi @yanivpaz, the issue will be closed and you can reopen it if you have more questions.

Thanks
