### ISSUE TITLE
How to sending logs to different destinations

### ISSUE THREAD

**Issue by bhargavamin** [aws/aws-for-fluent-bit#113]
Hi,

I wanted to ask if it is possible to split incoming logs to log router and sent them to a different location using firelense.

 For eg. app logs and ystem logs

- System logs should go to CloudWatch log group.
- App logs should go to Fluentd > ES > Kibana

Currently, all the logs go to a single location at a time using firelens.

Any help here would mean a lot. Thanks

**Comment by PettitWesley** [comment]
this might help: https://aws.amazon.com/blogs/opensource/splitting-application-logs-multiple-streams-fluent/

Read that. If it doesn't help then please give us more details on your setup.

**Comment by zhonghui12** [comment]
Hello @bhargavamin , I hope the link helped you solve the problem. this issue will be closed and please reopen it if you have more questions.

Thanks
