### ISSUE TITLE
Feature Request: Publish image onto ECR Public

### ISSUE THREAD

**Issue by furikake** [aws/aws-for-fluent-bit#123]
There are no images published on ECR Public Gallery: https://gallery.ecr.aws/aws-observability/aws-for-fluent-bit 

It would be good to publish it there so that we can simply use `public.ecr.aws/aws-observability/aws-for-fluent-bit:tag` as our container image.

Doing `aws ssm get-parameters-by-path --path /aws/service/aws-for-fluent-bit/` to parse the output is not user friendly at all.

**Comment by PettitWesley** [comment]
@furikake agreed- we created that repo since are working on this :)

The winter holidays and post-re:invent haze will probably slow things down a bit, but you'll see images there soon enough.

**Comment by zhonghui12** [comment]
Hello @furikake, the feature will be available in next release. Thanks for your patience.

**Comment by furikake** [comment]
Thanks @zhonghui12

**Comment by zhonghui12** [comment]
Hello @furikake, our images have been pushed to Amazon ECR Public Gallery in our recent release: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.10.1. You can check the public repo to see more details: https://gallery.ecr.aws/aws-observability/aws-for-fluent-bit.

The issue will be closed. Thanks.
