### ISSUE TITLE
Please support log_retention_days

### ISSUE THREAD

**Issue by somelinuxguy** [aws/aws-for-fluent-bit#131]
Configuration parameters to set log retention in the config, not manually in the console, would be an extremely useful feature.

FluentD:
        log_retention_days  3

FluentBit:
[error] [config] cloudwatch_logs: unknown configuration property 'log_retention_days'. The following properties are allowed: region, log_group_name, log_stream_name, log_stream_prefix, log_key, extra_user_agent, log_format, role_arn, auto_create_group, endpoint, sts_endpoint, metric_namespace, and metric_dimensions.

**Comment by PettitWesley** [comment]
This is supported for the `cloudwatch` plugin. Use that: https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit

It is coming for `cloudwatch_logs` soon, once Fluent Bit 1.7 comes out, its implemented but not released.

**Comment by zhonghui12** [comment]
Close this issue as the feature is supported for `cloudwatch_logs`: https://docs.fluentbit.io/manual/pipeline/outputs/cloudwatch#configuration-parameters.
