### ISSUE TITLE
Getting 'AccessDeniedException' 

### ISSUE THREAD

**Issue by HazemElAgaty** [aws/aws-for-fluent-bit#155]
Hey Guys, I have been following [these set of steps](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs-FluentBit.html) documented on AWS to deploy fluent bit agents on my EKS cluster. I have tried this on multiple clusters before and it was working as expected. 
However, I am trying to do the same exact steps on a newly created cluster by I am facing issues with permissions.

**Docker Version:** `amazon/aws-for-fluent-bit:2.10.0`
**Kubernetes Version:** `1.17`

**Logs:**
```
│ [2021/03/04 16:19:26] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Creating log group /aws/containerinsights/prod-cluster/application                                                                                                                                  │
│ [2021/03/04 16:19:26] [error] [aws_credentials] Could not read shared credentials file /root/.aws/credentials                                                                                                                                                                │
│ [2021/03/04 16:19:26] [error] [output:cloudwatch_logs:cloudwatch_logs.0] CreateLogGroup API responded with error='AccessDeniedException'                                                                                                                                     │
│ [2021/03/04 16:19:26] [error] [output:cloudwatch_logs:cloudwatch_logs.0] Failed to create log group                                                                                                                                                                          │
│ [2021/03/04 16:19:26] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Creating log group /aws/containerinsights/prod-cluster/application                                                                                                                                  │
│ [2021/03/04 16:19:26] [error] [output:cloudwatch_logs:cloudwatch_logs.0] CreateLogGroup API responded with error='ThrottlingException', message='Rate exceeded'                                                                                                              │
│ [2021/03/04 16:19:26] [error] [output:cloudwatch_logs:cloudwatch_logs.0] Failed to create log group                                                                                                                                                                          │
│ [2021/03/04 16:19:26] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Creating log group /aws/containerinsights/prod-cluster/application                                                                                                                                  │
│ [2021/03/04 16:19:26] [error] [output:cloudwatch_logs:cloudwatch_logs.0] CreateLogGroup API responded with error='AccessDeniedException'                                                                                                                                     │
│ [2021/03/04 16:19:26] [error] [output:cloudwatch_logs:cloudwatch_logs.0] Failed to create log group
```

I also double checked that the cluster has the needed IAM permissions. I am not sure what is missing here.
```
AmazonEKSClusterPolicy
AmazonEKSServicePolicy
```

**Comment by HazemElAgaty** [comment]
I had a misunderstanding regarding the IAM policies needed. My bad.

**Comment by Swisk** [comment]
Could you share what the issue was with the IAM policies? Am facing the same issue now with fluent bit on my EKS cluster.

**Comment by jjorissen52** [comment]
We are seeing this error with `CloudWatch` and `CloudWatch Logs` full access applied.

**Comment by pvrzl** [comment]
@Swisk @jjorissen52 

you can follow [these instructions](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-prerequisites.html) to solve the issue.

**Comment by harshbh98** [comment]
I faced the same issue while setting up fluent-bit in my eks cluster. Log groups were not getting created in cloudwatch. After a lot of workaround, I found the root cause in my case, this issue is **not related to credentials file**, but It is related to **IAM policies**.
When I assign the cloudWatchFullLogs policy to the `<eksnodegroup-role>` of my eks cluster, It worked. Though, CloudWatchFullLogs policy is not mandatory, you can assign limited permissions as well to the `<eksnodegroup-role>` as per your requirement. Thanks
