### ISSUE TITLE
S3 Plugin can't handle japanese characters

### ISSUE THREAD

**Issue by PettitWesley** [aws/aws-for-fluent-bit#167]
See the core issue: https://github.com/fluent/fluent-bit/issues/3280

This was originally reported by an AWS customer who saw the issue in the S3 output. The S3 output is just using some core code in Fluent Bit which isn't handling some unicode characters properly. Adding an issue in this repo to track it for our team.

**Comment by PettitWesley** [comment]
This is being fixed upstream: https://github.com/fluent/fluent-bit/pull/3284

**Comment by zhonghui12** [comment]
The fix has been released: https://fluentbit.io/announcements/v1.7.3/

**Comment by zhonghui12** [comment]
Close this one as the upstream issue has been fixed.
