### ISSUE TITLE
PutObject API responded with error='AccessDenied', message='Access Denied' using S3 plugin

### ISSUE THREAD

**Issue by qwegssg** [aws/aws-for-fluent-bit#168]
Hello, thank you for releasing the S3 plugin! Not sure if it is the right place to ask, but I was using aws-for-fluent-bit 2.12.0 as a sidecar container for a project in Amazon EKS, and added the s3 plugin as an output, however, when the upload timeout was reached, the logs showed:

[2021/03/25 21:12:54] [error] [aws_client] auth error, refreshing creds
[2021/03/25 21:12:54] [error] [aws_credentials] Could not read shared credentials file /root/.aws/credentials
[2021/03/25 21:12:54] [error] [output:s3:s3.1] PutObject API responded with error='AccessDenied', message='Access Denied'
[2021/03/25 21:12:54] [error] [output:s3:s3.1] Raw PutObject response: HTTP/1.1 403 Forbidden

I'm wondering how to **set up the credentials** for AWS in the Pod's ConfigMap, so that the S3 connection can be built?

Here is my S3 plugin related config:

fluent-bit.conf: |-

    [INPUT]
        Name tail
        Parser apache
        Path /logs/stdout*

    [OUTPUT]
        Name s3
        Match *
        bucket test
        region us-east-1
        store_dir /tmp/fluent-bit/s3
        total_file_size 50G
        upload_timeout 1m

**Comment by PettitWesley** [comment]
You don't add credentials in the config map. You use something like https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

Try out the EKS Workshop tutorials on setting up IAM: https://www.eksworkshop.com/beginner/110_irsa/
