### ISSUE TITLE
Feature request: tiny up docker image

### ISSUE THREAD

**Issue by lowerzero** [aws/aws-for-fluent-bit#17]
Currently image is around 553Mb which makes difficult to use as for example pod sidecar. Can we make it a reasonable or size without all unnecessary software installed. It can be multistage build for example

**Comment by ahmednasir91** [comment]
Any plans on this, i'm planning to use this plugin but its current size is 10x of the original fluent-bit image.

**Comment by hossain-rayhan** [comment]
Hi @ahmednasir91 , in the long run we have a plan to rewrite our existing Go plugins in C which will help to reduce the image size. For the existing approach, we are still investigating possible scopes and limitations on our side. Will post here once we have an update.

**Comment by ahmednasir91** [comment]
@hossain-rayhan i've added the kinesis plugin in the original fluent-bit image, it results in 95MB image size.
<img width="1682" alt="Screenshot 2020-05-05 at 10 53 59 PM" src="https://user-images.githubusercontent.com/1519532/81099357-3b9d9880-8f24-11ea-84a5-c3009781c368.png">

You can find the change here, what do you think of this approach? Any reason for using the Amazon Linux AMI ?
https://github.com/ahmednasir91/fluent-bit/commit/7232e5f0e3a9670de991cc450891f321c11c1029

**Comment by PettitWesley** [comment]
@ahmednasir91 We can consider that approach, but at the moment, an Amazon Linux base ensures that we can cover the image with AWS Support and can own any patches on it.

As Rayhan noted- we are in the process of re-writing our plugins in C and contributing them to the core of Fluent Bit. Once that happens, the fluent/fluent-bit Docker Hub image will have full AWS Support.

**Comment by PettitWesley** [comment]
I'll add that another reason is that we take software licensing very seriously. Most of the packages and code found in a linux base and container image is licensed such that the license text and attribution is supposed to be a part of any software release (i.e. this container image). With the Amazon Linux base, we can guarantee that all licenses and attributions are in place. We have not yet looked at the Distroless image to determine if it meets this requirement.
