### ISSUE TITLE
AWS cloudwatch, s3 and Kinesis, STS cross account access with external_id

### ISSUE THREAD

**Issue by hardwaysun** [aws/aws-for-fluent-bit#171]
1.7 version. Without external_id , cross account  works fine. 

But can't find the option to put in external_id in the cloudwatch, s3 or kinesis plugin config. Wondering does it supported? 

Can't find that in the c version too.

The Elasticsearch plugin have field "AWS_External_ID"

**Comment by DrewZhang13** [comment]
These are official website for these plugin.
[cloudwatch plugin](https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit)
[Kinesis Firehose plugin](https://github.com/aws/amazon-kinesis-firehose-for-fluent-bit)
[kinesis streams plugin](https://github.com/aws/amazon-kinesis-streams-for-fluent-bit)
[Fluent Bit C version](https://docs.fluentbit.io/manual/pipeline/outputs/)
Currently there is no `external_id` supported in these plugin.

**Comment by hardwaysun** [comment]
Are you guys planning to support it soon. If not I can add it and contribute to the community.
Thanks.

发自 Android 版 Yahoo 邮箱 
 
  2021 年 4 月 19 日周一上午 12:21，Drew ***@***.***> 写道：   


These are official website for these plugin.
cloudwatch plugin
Kinesis Firehose plugin
kinesis streams plugin
Fluent Bit C version
Currently there is no external_id supported in these plugin.

**Comment by PettitWesley** [comment]
https://github.com/fluent/fluent-bit/pull/4626
https://github.com/fluent/fluent-bit/pull/4625

**Comment by zhonghui12** [comment]
Close this issue as the feature is supported in latest release: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.22.0. Please feel free to reopen it for further questions.
