### ISSUE TITLE
Feature request: Loki output

### ISSUE THREAD

**Issue by dstockhammer** [aws/aws-for-fluent-bit#176]
It would be great to be able to send logs to Loki, see https://grafana.com/docs/loki/latest/clients/fluentbit/

If I understand correctly, the current workaround would be to ship to CloudWatch and export to Loki from there using Lambda. That seems like quite a complex setup.

**Comment by DrewZhang13** [comment]
Fluent bit currently already support Loki output. See the offical doc: https://docs.fluentbit.io/manual/pipeline/outputs/loki

**Comment by zhonghui12** [comment]
Close this issue for no follow up. Feel free to re-open it if you have more questions.
