### ISSUE TITLE
Failed to refresh token for aws elasticsearch

### ISSUE THREAD

**Issue by jerry153fish** [aws/aws-for-fluent-bit#187]
The aws elasticsearch is controller by the role acl, it seems that we had issue with the token refreshing 

```{"message":"The security token included in the request is expired"}```

**Comment by federico-cuello-solarisbank** [comment]
I think this is a dupe of https://github.com/aws/aws-for-fluent-bit/issues/186

**Comment by zhonghui12** [comment]
Hello @jerry153fish,

Fluent Bit had a new release 1.7.8 for fixing issues and we just cut a new release for `aws-for-fluent-bit` with Fluent Bit 1.7.8: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.15.1. Can you please try upgrade your image to the newest version to see if your problem has been fixed? Please post update here if it still doesn’t work.

Thanks for your help and patience.

**Comment by jerry153fish** [comment]
Looking good on my test cluster

**Comment by jerry153fish** [comment]
```
[2021/06/15 03:55:04] [ warn] [engine] chunk '1-1623729295.102050199.flb' cannot be retried: task_id=9, input=tail.0 > output=es.1
[2021/06/15 03:55:06] [error] [output:es:es.1] HTTP status=403 URI=/_bulk, response:
{"message":"The security token included in the request is invalid"}
```
I still have this error happening on `2.15.1`

**Comment by zhonghui12** [comment]
Hello @jerry153fish,

Can you please try 2.16.1 to see if the error still happens?

Thanks

**Comment by jerry153fish** [comment]
@zhonghui12 thanks will double check.

**Comment by jerry153fish** [comment]
@zhonghui12 it seems that everything works as expected now after a week's test in our dev clueter.
