### ISSUE TITLE
Can not pull latest (2.15.1) version in Fargate

### ISSUE THREAD

**Issue by freko247** [aws/aws-for-fluent-bit#194]
> A reproducible test case or series of steps

Deploying (pulling) `latest` in Fargate does not work, the following is logged:

```Stopped reason: CannotPullContainerError: inspect image has been retried 5 time(s): httpReaderSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/amazon/aws-for-fluent-bit/manifests/sha256:3b4efc1832605c5449308a726941410c28ded459110b31eeff5d001...```

Rolling back to `stable` works

> The version of our code being used

Current `latest` tag, or `2.15.1`

> Any modifications you've made relevant to the bug

None
> Anything unusual about your environment or deployment

None

**Comment by hossain-rayhan** [comment]
Interesting. I just tried in Fargate and its working for me. 

Image: `906394416424.dkr.ecr.us-east-1.amazonaws.com/aws-for-fluent-bit:latest`
Fargate Platform version: `1.4.0`

Can you share your Fargate platform version?

**Comment by freko247** [comment]
We are running on `1.4.0` as well

**Comment by freko247** [comment]
We were pulling `amazon/aws-for-fluent-bit:latest` (dockerhub), I can confirm the pulling `public.ecr.aws/aws-observability/aws-for-fluent-bit:latest` (ecr) works without any problems.

**Comment by hossain-rayhan** [comment]
HI @freko247, I tested with `amazon/aws-for-fluent-bit:latest` and its working fine. I feel like it might be a networking issue. What is the networking mode you have chosen. I tested with `awsvpc` and it works fine. 

Also for Fargate,
- If you're launching tasks in a public subnet, choose ENABLED for Auto-assign public IP when you launch a task in the Amazon EC2 console. This allows your task to have outbound network access to pull an image.
- If you're using an Amazon provided DNS in your Amazon VPC, confirm that the security group attached to the instance has outbound access allowed for HTTPS (port 443).

**Comment by PettitWesley** [comment]
Could this also be a dockerhub throttling problem? We strongly recommend that you do not use Docker Hub. Use ECR Public gallery or our regional ECR repos: https://github.com/aws/aws-for-fluent-bit#public-images

**Comment by PettitWesley** [comment]
Docker Hub is no longer reliable if you are not a logged in user: https://www.docker.com/increase-rate-limits

Thus AWS recommends using ECR Public: https://gallery.ecr.aws/aws-observability/aws-for-fluent-bit

**Comment by hossain-rayhan** [comment]
Hi @freko247, Do you still have issues with this? Can you share the update so that we can help or close this issue. Thanks.

**Comment by zhonghui12** [comment]
Close this issue as no response. Please feel free to re-open it if you have more problems.

Thanks.

**Comment by revett** [comment]
Can confirm moving to `public.ecr.aws/aws-observability/aws-for-fluent-bit:latest` fixed the issue.

**Comment by marksweb** [comment]
I've just had this happen, seemingly due to rate limiting by docker.

Switching the image to `public.ecr.aws/aws-observability/aws-for-fluent-bit:latest` sorted it
