### ISSUE TITLE
Question: How to tag auto-created cloudwatch groups?

### ISSUE THREAD

**Issue by bml1g12** [aws/aws-for-fluent-bit#203]
Sorry very new to all this so apologies if it is a bad question or posted in wrong repo. I am using EKS + aws-for-fluent-bit to log my EKS cluster to CloudWatch. It auto-created Cloudwatch log groups, but how do I set the tags for these automatically?

I saw https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit has a `new_log_group_tags` but even with the latest version of aws-for-fluent-bit (which I think is 2.16.1) this gives me the following error:

```
[2021/07/06 12:20:58] [error] [config] cloudwatch_logs: unknown configuration property 'new_log_group_tags'. The following properties are allowed: region, log_group_name, log_stream_name, log_stream_prefix, log_key, extra_user_agent, log_format, role_arn, auto_create_group, log_retention_days, endpoint, sts_endpoint, metric_namespace, and metric_dimensions.
[2021/07/06 12:20:58] [ help] try the command: /fluent-bit/bin/fluent-bit -o cloudwatch_logs 
````

Suggesting It is not implemented here. 

Thanks for any help

**Comment by PettitWesley** [comment]
@bml1g12 There are two cloudwatch plugins:
1. `cloudwatch` which is older and has support for tagging: https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit
2. `cloudwatch_logs` which is newer and more performant but does not have as many features: https://docs.fluentbit.io/manual/pipeline/outputs/cloudwatch

**Comment by bml1g12** [comment]
Thank you - I see so a plugin is the way to go here. As you say, it seems the older plugin "cloudwatch" has support for tagging, and as I understand it, it seems to be bundled in the image I am using (amazon/aws-for-fluent-bit:2.16.1) but how do I enable the plugin?

I can only see guidance on how to run it outside of the container (https://github.com/aws/aws-for-fluent-bit#using-the-aws-plugins-outside-of-a-container)

**Comment by PettitWesley** [comment]
In your config map, you probably have sections right now like:

```
[OUTPUT]
    Name cloudwatch_logs
   ...
```

That's an output configuration, just change the plugin name:

```
[OUTPUT]
    Name cloudwatch
   ...
```

https://aws.amazon.com/blogs/containers/kubernetes-logging-powered-by-aws-for-fluent-bit/

**Comment by bml1g12** [comment]
Oh wow nice thanks! I was imagining something way more complex. Seems to work, albeit it will be easier for me to test next time I spin up a new cluster (with new log groups)
