### ISSUE TITLE
2.17.0 Multiline parsers

### ISSUE THREAD

**Issue by tlamr** [aws/aws-for-fluent-bit#206]
Hi guys,

  we are trying to use 2.17.0 and multiline parser on bottlerocket on EKs but we are unable to figure out, how to configure it. Would you be able to help us?

Thanks,
Tomas

**Comment by tlamr** [comment]
Our failed attempts are here https://github.com/fluent/fluent-bit/issues/3778

**Comment by PettitWesley** [comment]
Interesting/thanks. I don't know anything about the new parser support besides what it says in the [docs](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing). May be there's something we need to do to compile it in our distro.

**Comment by zhonghui12** [comment]
Hello, Fluent Bit made a new release about the Multiline Filter and we support it in our latest version: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.18.0. Also, we have the example for using it: https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/filter-multiline. Hope it can help.

**Comment by zhonghui12** [comment]
Close this issue as the upstream issue has been closed and @tlamr mentioned in the upstream issue that it works for them.
