### ISSUE TITLE
2.17.0 multiline parsers breaks on pod restart

### ISSUE THREAD

**Issue by jngbng** [aws/aws-for-fluent-bit#210]
I tried `amazon/aws-for-fluent-bit:2.17.0` with following fluent bit setup:

```
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        multiline.parser  docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [OUTPUT]
        Name            es
        Match           *
        Generate_ID     On
        Logstash_Format On
```

(Other settings are taken from https://www.eksworkshop.com/intermediate/230_logging/deploy.files/fluentbit.yaml)

It seems work well for the beginning, inserting logs to ES index `logstash-2021.07.27`.

However, once I restart deployment, it starts to insert logs to ES index `logstash-1970.01.01` and all record's @timestamp is `1970.01.01 09:00`.

Once I restart deployment again, fluent bit fails to process logs with following error logs:
```
[2021/07/27 02:43:40] [error] [multiline] invalid stream_id 5750917875742300650, could not append content to multiline context
(...repeat)
```

Once I rollout fluent bit daemonsets, everything works well again.

Is built-in multiline parser still unstable or am I missing some setting?

**Comment by zhonghui12** [comment]
Multiline feature is supported in our latest image(2.18.0): https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.18.0. Please upgrade the image to check it. Thanks.

**Comment by jngbng** [comment]
@zhonghui12  Thanks for fast update! But it still happens.

I dug into the problem and it has something to do with fluent-bit itself. (Or I misunderstand this feature.) https://github.com/fluent/fluent-bit/issues/3872

And I found that new multiline.parser is unstable yet.  https://github.com/fluent/fluent-bit/issues/3840
