### ISSUE TITLE
🚨 2.17.0 Tag was accidentally over-written 🚨

### ISSUE THREAD

**Issue by PettitWesley** [aws/aws-for-fluent-bit#214]
Hey folks, unfortunately, due to a bug in the AWS for Fluent Bit release process, we over-wrote the old image tag for 2.17.0 with the new contents of the 2.19.0 image. We are working on remedying this and ensuring it can not happen again.

Apologies for any inconvenience this causes.

**Comment by DrewZhang13** [comment]
issue has been fixed now and 2.19.0 version is available to use now
