### ISSUE TITLE
Fluent-bit sidecar is killed because of networking timed out 

### ISSUE THREAD

**Issue by uname-yang** [aws/aws-for-fluent-bit#223]
Opening here for visibility
please see  for details on the issue: [amazon-kinesis-streams-for-fluent-bit/issues/154](https://github.com/aws/amazon-kinesis-streams-for-fluent-bit/issues/154)
we're experiencing with the core kinesis_streams plugin.

**Comment by hossain-rayhan** [comment]
As per Wesleys suggestion in the other issue, can you try upgrading to 2.19.0 and let us know if you see the same issue? 2.19.0 contains a new version of core fluent bit. In the meantime we will try repro and get a stack trace.

**Comment by uname-yang** [comment]
We switch to the `kinesis` plugin. It's OK now.
