### ISSUE TITLE
Pulling container failing with unexpected status code

### ISSUE THREAD

**Issue by babaMar** [aws/aws-for-fluent-bit#234]
ECS is not able to pull the containers, getting this error message:

```
CannotPullContainerError: inspect image has been retried 5 time(s): httpReaderSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/amazon/aws-for-fluent-bit/manifests/sha256:330a24bcd4e0058d70e70a0bb1ff805065161ffe3aa96296f09b555...
```

**Comment by zhonghui12** [comment]
Hi @babaMar, could I know which version you are pulling and could I list the steps you pull the image? Thanks.

**Comment by babaMar** [comment]
@zhonghui12 I'm pulling the `latest` tagged image from ECS. So basically in the `ContainerDefinitions` of the `AWS::TaskDefinition` resource I have `Image: aws-for-fluent-bit:latest'`.

It worked until yesterday

**Comment by amopportunities** [comment]
I am also having the same issue.

**Comment by PettitWesley** [comment]
@babaMar Unfortunately I have no clue why this happened... we don't recommend using the docker hub image though... docker hub recently added pull limits... use the Public ECR image instead: https://github.com/aws/aws-for-fluent-bit#amazon-ecr-public-gallery

**Comment by zhonghui12** [comment]
Hi @babaMar, any update here? Please let me know if our public ECR image helps.

**Comment by zhonghui12** [comment]
Close this one for no response. Please feel free to reopen it if the problem still exists.
