### ISSUE TITLE
Any windows container version?

### ISSUE THREAD

**Issue by kingsleykumar** [aws/aws-for-fluent-bit#244]
Hi team, Does this work on windows machines? Is there any separate version available for windows containers? 

Thanks.

**Comment by DrewZhang13** [comment]
Currently there is no support for windows version.

**Comment by zhonghui12** [comment]
We have an issue to track the windows support so please +1 [here](https://github.com/aws/aws-for-fluent-bit/issues/129) if you have the same request. Will close this one for same requirement.
