### ISSUE TITLE
When will v2.18.0+ be moved to stable image release?

### ISSUE THREAD

**Issue by jmreicha** [aws/aws-for-fluent-bit#272]
### Describe the question/issue

It would be useful to get the `multiline` functionality into the stable version, I am wondering what the timeline/process for this might be?

I saw the guidelines [here](https://github.com/aws/aws-for-fluent-bit#using-the-stable-tag) but it looks like the stable image version hasn't been updated since v2.16.1 (end of June).

### Fluent Bit Version Info

stable:
 * fluentbit - v1.7.9
 * aws-for-fluent-bit - 2.16.1

latest:
* fluentbit - 1.8.9
* aws-for-fluent-bit - 2.21.1

### Steps to reproduce issue

`docker run -it --rm public.ecr.aws/aws-observability/aws-for-fluent-bit:stable /fluent-bit/bin/fluent-bit --version`
`docker run -it --rm public.ecr.aws/aws-observability/aws-for-fluent-bit:stable cat /AWS_FOR_FLUENT_BIT_VERSION`

### Related Issues

https://github.com/aws/aws-for-fluent-bit/issues/100

**Comment by zhonghui12** [comment]
We are planning to mark our latest image as the stable version as we identified different issues in images < 2.21.2. If everything looks fine till next week, then the stable version will be advanced.

**Comment by jmreicha** [comment]
Sounds good, thanks for the update!

**Comment by SatyaVadapalli** [comment]
@zhonghui12 

Any update on this? We are are planning to use Firelens on AWS ECS Fargate with Fluent Bit.We are able to stream the logs from the app container to the CloudWatch.But multiline logs(java stacktrace) are coming as separate log events on cloudwatch.We need multiline log as a single event on cloudwatch logs.

Is this fixed in v2.18.0+ ? If so any ETA ?

But ,For now we would like to give a try on using fluentd .But will we face the same issue with fluentd as well?
Please let us know.

**Comment by zhonghui12** [comment]
Hi everyone, the stable version has already been moved to 2.21.3: https://github.com/aws/aws-for-fluent-bit/blob/mainline/AWS_FOR_FLUENT_BIT_STABLE_VERSION.

**Comment by zhonghui12** [comment]
Hi @SatyaVadapalli, multiline issue has been fixed with tail input plugin: https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-core-v1.8. But with multiline filter plugin is still broken, more details can be found in this issue: https://github.com/fluent/fluent-bit/issues/4309.

**Comment by jmreicha** [comment]
@zhonghui12 is there an example of how to use the tail plugin in the repo somewhere?

**Comment by zhonghui12** [comment]
Hi @jmreicha, the multiline filter plugin now is broken so the example doesn't work now. An example of using `tail` plugin in ecs can be found here: https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/ecs-log-collection#tutorial-1-tail-log-files-and-capture-stdout

**Comment by jmreicha** [comment]
Got it, thanks!
