### ISSUE TITLE
CloudWatch Metrics Discarding massive log record [Mirror issue from upstream fluent-bit #4425]

### ISSUE THREAD

**Issue by krispraws** [aws/aws-for-fluent-bit#282]
This issue was originally reported by user [markuman](https://github.com/markuman) in the upstream fluent-bit repository as [Issue #4425](https://github.com/fluent/fluent-bit/issues/4425).

### Short Summary
When publishing cpu/memory metrics in EMF format to CloudWatch logs, the code allocates memory for the created msgpack object but then also frees it and returns a pointer to the (now) invalid memory chunk.

The [two lines](https://github.com/fluent/fluent-bit/commit/f06525a18d4ff72f855bbef67ea68f258901fb98#diff-d70aca905ecc02fb9ccb4518905d0caefe2a8e5254b4cbe69dc930291be75be4R774
) here are the problem.

Possible solutions:
- (Short term) Pass a reference to the msgpack zone/buffer so that the code that unpacks the object can free it.
- (Medium term) Get rid of the msgpack for emf metrics and handle them directly when processing log events to send to CW. The current implementation lets other functions (in the same file) always expect msgpack input which is nice. But it adds additional complexity and overhead of packing and unpacking msgpack objects between functions that are executed sequentially without any suspension points.

### Details
Refer to [Issue #4425](https://github.com/fluent/fluent-bit/issues/4425) for details on the bug and steps to reproduce.

**Comment by krispraws** [comment]
PR submitted: https://github.com/fluent/fluent-bit/pull/4563

**Comment by matthewfala** [comment]
Thank you @krispraws.
This patch has been included in Fluent Bit 1.8.12 and aws-for-fluent-bit image version 2.22.0. Please see the release notes here: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.22.0
