### ISSUE TITLE
SIGSEGV with cloudwatch_logs in 2.22.0 

### ISSUE THREAD

**Issue by PettitWesley** [aws/aws-for-fluent-bit#300]
This is a friendly note that we have seen some SIGSEGV crashes on 2.22.0 when the `cloudwatch_logs` output is used. 

We are actively investigating this. It's not clear if only `cloudwatch_logs` is the real trigger, or something else is the cause. 

In the meantime, please use an older version or try our stable release which we have high confidence in: https://github.com/aws/aws-for-fluent-bit/blob/mainline/AWS_FOR_FLUENT_BIT_STABLE_VERSION

**Comment by PettitWesley** [comment]
I was able to repro the crash with a simple cloudwatch_logs output in FireLens. No other plugins were used.

**Comment by PettitWesley** [comment]
I've also gotten a report of an OOMKill on 2.22.0 that looks like a real memory leak since the memory usage went over 2 GB without terribly high throughput. Have not repro'd this myself though.

**Comment by PettitWesley** [comment]
Unfortunately I have utterly failed thus far to repro this segfault in a way that gets me a stack trace so I can figure out what its caused by. I am very embarrassed by this and I am still working on it.

In the meantime we will release 2.23.0 with Fluent Bit 1.8.13 to get the latest upstream code out to our customers. We will mark in this issue if we eventually determine that the new version also suffers from the same issue. 

As a reminder, prod deployments should use our stable version, unless you have a sophisticated testing setup and feel confident that you have vetted a newer release: https://github.com/aws/aws-for-fluent-bit/blob/mainline/AWS_FOR_FLUENT_BIT_STABLE_VERSION

**Comment by matthewfala** [comment]
Do you think it could be a bad api response we were getting periodically from CW? That way if CW team fixed the response the segfault would go away and the results would not be fluent bit source dependent.

What do you think?

**Comment by PettitWesley** [comment]
I'm gonna close this since we have no confirmation from anyone else. Investing in fuzz testing is a good long term action item.

**Comment by matthewfala** [comment]
Do you think it could be a bad api response we were getting periodically from CW? That way if CW team fixed the response the segfault would go away and the results would not be fluent bit source dependent.

What do you think?
