### ISSUE TITLE
Creating a config file that specifies multiple outputs + JSON conversion

### ISSUE THREAD

**Issue by metersk** [aws/aws-for-fluent-bit#304]
### Describe the question/issue
I currently have firelens + fluentbit set up to send logs to cloudwatch and datadog.  This is working and I am able to see logs in both places.  The cloudwatch logs are coming through as serialized JSON that I would like to be parsed.

I took a look [here](https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/parse-json) and it recommends setting the following options on the `FirelensConfiguration`

```
        "config-file-type": "file",
        "config-file-value": "/fluent-bit/configs/parse-json.conf"
```

Since I am sending logs to two outputs I need a different custom custom file for `config-file-value`.  I tried copying the contents of `extra.conf` into `logDestinations.conf` like the below, but i was still seeing serialized JSON in cloudwatch.  Is there anything else I should be modifying or adding to parse the serialized cloudwatch JSON?

```
[SERVICE]
    Parsers_File /fluent-bit/parsers/parsers.conf
    Flush 1
    Grace 30

[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser json
    Reserve_Data True

[OUTPUT]
    Name  cloudwatch_logs
    Match   *
    region us-east-1
    log_group_name      /galileo/cluster/fargate
    log_stream_prefix   api/application/
    auto_create_group On   
[OUTPUT]
    Name              datadog
    Match             application
    Host              http-intake.logs.datadoghq.com
    TLS               on
    compress          gzip
    apikey            <API-KEY>
    dd_service        staging-api
    dd_source         flask
    dd_message_key    log
    dd_tags           env:staging:api
    provider          ecs
    ```

**Comment by zhonghui12** [comment]
> Since I am sending logs to two outputs I need a different custom custom file for `config-file-value`

Do you mean you generate a custom parse file `parsers.conf`?  If then, you need to change this path `Parsers_File /fluent-bit/parsers/parsers.conf` to your file. Current path is built into fluent bit image and if you change it, you need to update to your own.

**Comment by metersk** [comment]
@zhonghui12 No, sorry if I was not clear.  The directions [here](https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/parse-json) say that in order to parse serialized JSON you can do the following in a Fargate task
```
"firelensConfiguration": {
    "type": "fluentbit",
    "options": {
        "config-file-type": "file",
        "config-file-value": "/fluent-bit/configs/parse-json.conf"
    }
},
```
However, since I am trying to do additional things (multiple outputs, which require a custom config file) besides parsing the serialized JSON, I can't do the simple solution above.  I figured that I should be able to add the contents of `/fluent-bit/configs/parse-json.conf` to my custom log file, but this did not work.  I am following the instructions [here](https://aws.amazon.com/premiumsupport/knowledge-center/ecs-container-log-destinations-fargate/) for creating my custom logfile for multiple outputs. Essentially, how can I do [this](https://aws.amazon.com/premiumsupport/knowledge-center/ecs-container-log-destinations-fargate/) AND parse the serialzed JSON of the cloudwatch output.

**Comment by matthewfala** [comment]
@metersk What exactly are you expecting the parsed json to look like?

Like the following?
```
{
    "source": "stdout",
    "container_id": "e54cccfac2b87417f71877907f67879068420042828067ae0867e60a63529d35",
    "container_name": "/ecs-demo-6-container2-a4eafbb3d4c7f1e16e00"
    "ecs_cluster": "mycluster",
    "ecs_task_arn": "arn:aws:ecs:us-east-2:01234567891011:task/mycluster/3de392df-6bfa-470b-97ed-aa6f482cd7a6",
    "ecs_task_definition": "demo:7"
    "ec2_instance_id": "i-06bc83dbc2ac2fdf8"
    "requestID": "b5d716fca19a4252ad90e7b8ec7cc8d2",
    "requestInfo": {
        "ipAddress": "204.16.5.19",
        "path": "/activate",
        "user": "TheDoctor"
    }
}
```

Your config file should expand the json in the "log" key.

Could you please send an example of what you expect the log to look like at cloudwatch destination and what it actually looks like?

**Comment by metersk** [comment]
hello, sorry i was away from my computer for a few days.  i'm not sure how, but it seems to be be outputting parsed JSON into cloudwatch now (like you have posted).  i am using the config i have posted in the OP and can confirm that it does now work.  thanks and sorry for this erroneous issue report.

**Comment by matthewfala** [comment]
Great! @metersk  Thanks for the update. Glad you got things working now.
