### ISSUE TITLE
Output plugin 'cloudwatch' cannot be loaded 2.22.0

### ISSUE THREAD

**Issue by hcm-skreiss** [aws/aws-for-fluent-bit#305]
Good Afternoon,

Apologies if this has been answered somewhere already, or if the answer is obvious. I've been looking through the documentation for this image as well as the plugin itself, and I've looked through the issue history to no avail.

At the company I work for, I'm setting up log shipping for application logs from within our EKS cluster to Cloudwatch using Fluentbit. The problem is pretty simple, I'm attempting to use the older "cloudwatch" output plugin since I need the log stream/group templating functionality that the newer "cloudwatch_logs" plugin does not have. When I attempt to run the aws-for-fluent-bit image as a daemonset in the EKS cluster (using "cloudwatch" as the output plugin), one of the first log lines is "Output plugin 'cloudwatch' cannot be loaded".  The inputs are shown to be discovering the "tail" files correctly, but since the output plugin is not loaded, it makes no attempt to ship the logs to cloudwatch.

My config is very simple. To reproduce this, all you should have to do is have 1 tail input, and 1 "cloudwatch" output. Also tested with "cloudwatch_logs", that plugin seems to load fine, but obviously it can't parse the stream/group names correctly for lack of templating capabilities. I can post the config file if needed.

I've tried with multiple image versions other than 2.22.0, including the most recent stable release. Haven't been able to get any to work so far. Setting the log level to "debug" has added no additional information about why the plugin can't be loaded.

I was under the impression that the "cloudwatch" plugin was included with the aws-for-fluent-bit image, and from the documentation it seems like all I should have to do to enable it is reference it by name. Is there another place I have to enable it? I made sure the entrypoint.sh inside the container is using "-e fluent-bit/cloudwatch.so".

Any information would be appreciated, apologies again if the answer is obvious or if I haven't searched enough.

Thank you,
Stephen

**Comment by zhonghui12** [comment]
Hi @hcm-skreiss ,
`cloudwatch` plugin is included within the aws-for-fluent-bit image and you don't need to change the entrypoint.sh file. All you need to do is to use some config like https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit#example-fluent-bit-config-file. Could you please attach your config file if possible? Thanks.

**Comment by hcm-skreiss** [comment]
Thanks for replying @zhonghui12 

Here is the config I'm testing with at the moment:

`kind: ConfigMap
metadata:
  name: fluent-bit-config-kafka-rest
  namespace: logging
apiVersion: v1
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush          5
        Daemon         Off
        Log_Level      info
        Parsers_File   /fluent-bit/parsers/parsers.conf
    [INPUT]
        Name           tail
        Tag            am.debug
        Path           /mnt/log/am/*/debug/*
        DB             /mnt/log/flb_kube.db
        Multiline.Parser docker, cri
        Mem_Buf_Limit  5MB
        Read_from_Head True
    [FILTER]
        Name           kubernetes
        Match          kube.*
        Kube_URL   https://kubernetes.default.svc:443
    [OUTPUT]
        Name cloudwatch
        Match   *
        region us-west-2
        log_group_name dev/test-group
        log_stream_name test-stream
        auto_create_group On`

**Comment by hcm-skreiss** [comment]
Found the problem, there was a line in the daemonset manifest that was overwriting the entrypoint command and did not have the "-e cloudwatch.so" statement it needed.
