### ISSUE TITLE
Pushed logs from the fluent bit is taking around 20 to 30 minutes to get reflects in the cloud watch .   

### ISSUE THREAD

**Issue by sachin064** [aws/aws-for-fluent-bit#308]
pushed logs are getting delayed about 20 to 30 minutes in cloud watch, what may be solution, any suggestions that would be  really  help full,

my config as follows, am using aws for fluent bit .

[Output]
        Name cloudwatch_logs
        Match *
        region cloudwatch-log-region" 
        log_group_name {{ include "cloudwatch-log-group-name" . }}
        log_stream_prefix fluent-bit-
        auto_create_group true
        extra_user_agent  container-insights

**Comment by matthewfala** [comment]
Hi, 

The first thing that could help would be if you used the std_out output plugin https://docs.fluentbit.io/manual/pipeline/outputs/standard-output
and checked to see if the logs are immediately coming through to your standard out. If not, then the delay is most likely before fluent bit.

If the logs are coming through immediately, could you please send your Fluent Bit logs?
Please set your log_level to debug.
```
[SERVICE]
    Log_Level       debug
```
Could you check these debug logs to see if logs are immediately being sent to cloudwatch? Are some logs being immediately shown in Cloudwatch, or all logs are delayed by 30 minutes.
Maybe try set auto_retry_requests to true and see if this helps.

**Comment by matthewfala** [comment]
Closing due to no response, please feel free to reopen if you have anything further to discuss.
