### ISSUE TITLE
Stable Tag promotion

### ISSUE THREAD

**Issue by f0o** [aws/aws-for-fluent-bit#317]
(discarded issue template as it's inapplicable)

I noticed that Stable tag is still on 2.21.3 which released on 03 Dec 2021.

I understand that stable is meant to be a trusted stable version however anything before 2.21.5 I believe was suffering from that TCP-endless-hang that caused fargate/ecs to SIGKILL the container and spew alerts.

Is there any blocker that keeps `stable` on a soon 4 months old version?

**Comment by DrewZhang13** [comment]
Hi @f0o, for stable tag, we will review it every two weeks. Considering the several following versions after 2.21.3 basically still have known bugs that make it hard for us to find a real stable version, so we just keep it for now. I can bring this up and review the stable version with team see if any recent version don't have known issue and last for a while which could be called stable. We will adjust it based on the review result. 

Also stable version not blocking customer from using new versions so feel free to upgrade the version if 2.21.3's issue is blocking you based on your use case.

**Comment by f0o** [comment]
Any news regarding this? @DrewZhang13

**Comment by PettitWesley** [comment]
We need to promote stable. Will do that today.
