### ISSUE TITLE
Update to fluentbit 1.4

### ISSUE THREAD

**Issue by snemetz** [aws/aws-for-fluent-bit#32]
When can we expect this to be updated to fluentbit 1.4?
I need the new tag rewrite plugin

**Comment by hossain-rayhan** [comment]
Hi @snemetz, thanks for creating the issue. We released a new image with FluentBit 1.4.2- [AWS for Fluent Bit 2.3.0](https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.3.0)

**Comment by snemetz** [comment]
Thank You
