### ISSUE TITLE
AWS for fluentbit deployment type with service

### ISSUE THREAD

**Issue by vladpanainte** [aws/aws-for-fluent-bit#331]
### Describe the question/issue

We have an use case where we want to send logs from a service into an HTTP INPUT and setup aws-for-fluent-bit as deployment with service and  push the logs from another server here and then have kinesis firehose as output for this logs. The service that sends the logs will use HTTP input. This is not a use case for kubernetes logs. These logs follow an authorization flow first.

**Comment by vladpanainte** [comment]
Does aws for fluentbit support HTTP Input? https://docs.fluentbit.io/manual/pipeline/inputs/http

**Comment by zhonghui12** [comment]
> Does aws for fluentbit support HTTP Input? https://docs.fluentbit.io/manual/pipeline/inputs/http

yes, you could use HTTP input in [INPUT] field

**Comment by vladpanainte** [comment]
This questions was actually more for - https://github.com/aws/eks-charts/tree/master/stable/aws-for-fluent-bit to ask if there is a deployment typr available or plan for it.

**Comment by zhonghui12** [comment]
Could you please clarity a little bit? Do you you want one fluent bit per node with http input accepting events from all pods on the host or you want fluent bit server as a sidear?

**Comment by vladpanainte** [comment]
Hello. Thanks for the reply. We want to deploy aws-for-fluent-bit as deployment type with a service where we should expose the HTTP INPUT and scale if needed. We are working on customizing this chart but wondering if the deployment support type will be added. 

Regards,
Vlad

**Comment by zhonghui12** [comment]
@vladpanainte ,

This chart is just a template for our most common use cases (running Fluent Bit as a daemonset) but you could also customize the deployment manifests in EKS yourself to deploy aws-for-fluent-bit as deployment type. We might not support deployment type in a short term. 

Thanks.

**Comment by vladpanainte** [comment]
@zhonghui12  Thanks for your reply. This is something that we're already doing this just wanted to ask if this is in plan and if there is a roadmap for this.

Thanks!

**Comment by matthewfala** [comment]
Hi @vladpanainte, currently this is not on the FireLens roadmap and the configuration we provide is for daemon-sets, but you can always create your own configuration to solve your own usecases.
