### ISSUE TITLE
utf8 codes instead of symbols being sent to Cloudwtach by Cloudwatch plugin

### ISSUE THREAD

**Issue by ImBeeMaster** [aws/aws-for-fluent-bit#341]
### Question

I have an application in the ECS Fargate deployment, that emits logs to its filesystem, the log message includes symbols as '<' and '>' for example '<dependency_failed>'.  This log message is then captured by the Firelens, and sent to the CloudWatch. However, in the CouldWatch I see that its symbols < and > are converted to utf8 and the message looks like this:
{"log":"\u003cdependency_failed\u003e"}
Is it possible to send "decoded" symbols to the Cloudwatch? So that the message would look like:
{"log":"<dependency_failed>"}
 I know there's a "decoder" for the Parser however it works only when an initial string has the json structure and a json key is available for example when the docker log file is read, but in case of fluentbit reading the raw data from an application log file (compared to docker logs) the record is converted to json somewhere during the fluentbit record processing and not on the initial [input] section.

For the debugging purposes I spun up the following setup:

### Configuration
docker-compose.yaml :
version: "3.7"

services:
  fluent-bit-new:
    image: public.ecr.aws/aws-observability/aws-for-fluent-bit:latest
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit-parsers.conf:/fluent-bit/etc/fluent-bit-parsers.conf
      - type: bind
        source: ./shared/
        target: /tmp/shared/
    environment:
      - AWS_ACCESS_KEY_ID=<>
      - AWS_SECRET_ACCESS_KEY=<>
      - AWS_SESSION_TOKEN=<>

fluent-bit.conf :
[SERVICE]
    Parsers_File fluent-bit-parsers.conf

[INPUT]
    Name        tail
    Tag         dummy.data
    Path        /tmp/shared/log.log

[OUTPUT]
    Name   stdout
    Match  *

[OUTPUT]
    Name   file
    Match  *
    Path /tmp/shared/

[OUTPUT]
    Name cloudwatch
    Match   *
    region eu-west-1
    log_retention_days 1
    log_group_name /test/log_group
    log_stream_name error.json
    auto_create_group true

fluent-bit-parsers.conf :
[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S %z
    Decode_Field_as escaped_utf8 log

### Fluent Bit Log Output 

fluent-bit-new_1  | Fluent Bit v1.8.15
fluent-bit-new_1  | * Copyright (C) 2015-2021 The Fluent Bit Authors
fluent-bit-new_1  | * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
fluent-bit-new_1  | * https://fluentbit.io
fluent-bit-new_1  | 
fluent-bit-new_1  | AWS for Fluent Bit Container Image Version 2.23.3time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter log_group_name = '/test/log_group'"
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter default_log_group_name = 'fluentbit-default'"
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter log_stream_prefix = ''"
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter log_stream_name = 'error.json'"
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter default_log_stream_name = '/fluentbit-default'"
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter region = 'eu-west-1'"
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter log_key = ''"
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter role_arn = ''"
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter auto_create_group = 'true'"
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter new_log_group_tags = ''"
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter log_retention_days = '1'"
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter endpoint = ''"
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter sts_endpoint = ''"
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter external_id = ''"
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter credentials_endpoint = "
fluent-bit-new_1  | time="2022-05-04T11:24:43Z" level=info msg="[cloudwatch 0] plugin parameter log_format = ''"
fluent-bit-new_1  | [2022/05/04 11:24:43] [ info] [engine] started (pid=1)
fluent-bit-new_1  | [2022/05/04 11:24:43] [ info] [storage] version=1.1.6, initializing...
fluent-bit-new_1  | [2022/05/04 11:24:43] [ info] [storage] in-memory
fluent-bit-new_1  | [2022/05/04 11:24:43] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
fluent-bit-new_1  | [2022/05/04 11:24:43] [ info] [cmetrics] version=0.2.2
fluent-bit-new_1  | [2022/05/04 11:24:43] [ info] [sp] stream processor started
fluent-bit-new_1  | [2022/05/04 11:24:43] [ info] [input:tail:tail.0] inotify_fs_add(): inode=45154343 watch_fd=1 name=/tmp/shared/log.log
fluent-bit-new_1  | [2022/05/04 11:24:43] [ info] [output:file:file.1] worker #0 started
fluent-bit-new_1  | [2022/05/04 11:24:43] [ info] [output:stdout:stdout.0] worker #0 started
fluent-bit-new_1  | [0] dummy.data: [1651663487.847703115, {"log"=>"<dependency_failed>"}]
fluent-bit-new_1  | time="2022-05-04T11:24:53Z" level=info msg="[cloudwatch 0] Log group /test/log_group already exists\n"
fluent-bit-new_1  | time="2022-05-04T11:24:53Z" level=info msg="[cloudwatch 0] Set retention policy on log group /test/log_group to 1d\n"

### Fluent Bit Version Info

v1.8.15

### Steps to reproduce issue

When the docker-compose service is up it will read from file /tmp/shared/log.log which is bind mount so just white to it's mounted location:
mkdir shared
docker-compose up -d
echo '<dependency_failed>'>> shared/log.log

### Additional notes
Also note that in case "log_key log" parameter is included to cloudwatch output plugin, like so:

[OUTPUT]
    Name cloudwatch
    Match   *
    region eu-west-1
    log_retention_days 1
    log_key log
    log_group_name /test/log_group
    log_stream_name error.json
    auto_create_group true
    
Only the original string is sent to the Cloudwatch, and it's in fact looks like '<dependency_failed>' there (without utf8 conversion), but it's not suitable for me as cloudwatch plugin includes ecs metadata to the json so that resulting records looks like:

{
    "ecs_cluster": "OurCluster-dev-ecs",
    "ecs_task_arn": "arn:aws:ecs:eu-west-1:<acc id>:task/OurCluster-dev-ecs/95d56b9b73be4d9e9384a7d48a3fd2f1",
    "ecs_task_definition": "OurCluster-dev-ecsTaskDefinition417BCE0E:14",
    "log": "<dependency_failed>"
}
And I want to use these metadata fields further down

**Comment by ImBeeMaster** [comment]
actually, this doesn't appear for cloudwatch_logs plugin, but I wish it allows $(ecs_task_id) and $(ecs_cluster) in the Log Group and Stream Names templating

**Comment by matthewfala** [comment]
Hi @ImBeeMaster,
Thank you for letting me know cloudwatch_logs plugin does not have this issue as I was going to look into the code for this. Metadata templating is a common request, and we may add support for this in the future. Thank you for voicing your interest in this feature. It helps add priority.

For now, you can use an inefficient workaround to get a logstream with your ecs_cluster name via the rewrite_tag.
This is known to slow down the throughput FluentBit can handle and templating will be preferred if implemented.

```
[FILTER]
    Name          rewrite_tag
    Match         *
    Rule          $ecs_task_arn ^(.*)$  $TAG-$ecs_task_arn false
    Emitter_Name  re_emitted

[OUTPUT]
    # general cloudwatch_logs configuration (nothing special here, customize to fit your use case)
    Name                cloudwatch_logs
    Match               *
    log_group_name      myGroup
    log_stream_prefix   myStreamPrefix
    ...
```

This should change the tag of your log from `myTag` to `myTag-{someTaskArn}`. Then when sent to cloudwatch, the tag prefixed with log_stream_prefix and used as a log stream name.

Let me know if this is sufficient.

**Comment by ImBeeMaster** [comment]
Hi @matthewfala,
Sorry for taking too long to respond, I've already dropped the idea of log stream per task in favor of having one log stream and filtering though it with cloudwatch filter patterns. 
However, I also tried to validate your solution, it worked fine with some modifications:

```
[FILTER]
    Name          rewrite_tag
    Match         *
    Rule          $ecs_task_arn (task\/.*\/.*)$  $0 false
    Emitter_Name  re_emitted
```
otherwise the rule captures `arn:aws:ecs:eu-west-1:010100101011:task/my-cluster-name/712414610e6942f98d888327164474a0` and cloudwatch fails with `validation error detected: Value 'myStreamPrefix-arn:aws:ecs:eu-west-1:010100101011:task/my-cluster-name/712414610e6942f98d888327164474a0' at 'logStreamName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^:*]*'` (apparently cloudwatch doesen't like colons)
