### ISSUE TITLE
A new higher performance Firehose plugin has been released; you are using the old plugin

### ISSUE THREAD

**Issue by jseiser** [aws/aws-for-fluent-bit#345]
### Describe the question/issue

Is there any plans or way to use the newer Firehose plugin?

```
AWS for Fluent Bit Container Image Version 2.23.3time="2022-05-06T17:42:39Z" level=info msg="A new higher performance Firehose plugin has been released; you are using the old plugin. Check out the new plugin's documentation and consider migrating.\nhttps://docs.fluentbit.io/manual/pipeline/outputs/firehose"
```

### Fluent Bit Version Info

Fluent Bit v1.8.15

**Comment by matthewfala** [comment]
Hi, yes. You can use the new plugin by using kinesis_firehose instead of firehose as your plugin. Please see
https://docs.fluentbit.io/manual/pipeline/outputs/firehose
