### ISSUE TITLE
kube_token_ttl refreshes every 10 seconds rather than 10 minutes in 2.25.0

### ISSUE THREAD

**Issue by andytson** [aws/aws-for-fluent-bit#353]
### Describe the question/issue

The patches introducing the kube_token_ttl fail to change the type of the configuration to FLB_CONFIG_MAP_TIME, so 10m is treated as 10 seconds.

With kube_token_ttl having type FLB_CONFIG_MAP_INT, atoi() is used to parse the default value 10m, which returns 10. Instead FLB_CONFIG_MAP_TIME should be used so 10m is parsed as 600, as per the upstream PR https://github.com/fluent/fluent-bit/pull/4487

I identified the issue in the fork you use for patches https://github.com/PettitWesley/fluent-bit/pull/4/files

### Configuration

default

### Fluent Bit Log Output 

n/a

### Fluent Bit Version Info

2.25.0

### Steps to reproduce issue

Deploy 2.25.0 to an EKS cluster, see the token being fetched every 10 seconds

**Comment by DrewZhang13** [comment]
@andytson Checked [upstream](https://github.com/fluent/fluent-bit/blob/master/plugins/filter_kubernetes/kubernetes.c#L858) and there is no such issue. The issue only show in the fork: https://github.com/PettitWesley/fluent-bit/pull/4/files. May i ask why you are using that fork which is kind of personal fork? Is it possible for you to switch to official upstream?

**Comment by PettitWesley** [comment]
@DrewZhang13 @andytson there is part of the cherry pick we added in our recent release, we released code before upstream released. However, I thought I had done the cherry pick correctly so that it defaults to 10m... this is one of our cherry picked commits: https://github.com/PettitWesley/fluent-bit/commit/0527e1a2e903915a441e263e56827e8724d92d77

https://github.com/aws/aws-for-fluent-bit/blob/mainline/AWS_FLB_CHERRY_PICKS

**Comment by chi-bd** [comment]
@PettitWesley 

@andytson says "commit [8c84c5994d3ed1fa05fb3c1a60313792901a7623](https://github.com/PettitWesley/fluent-bit/commit/8c84c5994d3ed1fa05fb3c1a60313792901a7623) is missing".
("FLB_CONFIG_MAP_INT" should be "FLB_CONFIG_MAP_TIME" for parsing string "10m")

**Comment by andytson-inviqa** [comment]
yes, `FLB_CONFIG_MAP_TIME` bit is missing, not the `10m`

**Comment by PettitWesley** [comment]
@andytson I see. Thanks and Apologies for this. We will draft a new release today to fix it.

**Comment by PettitWesley** [comment]
New commit: https://github.com/PettitWesley/fluent-bit/commit/03276f84723b74ef3d3b3c83c2b71f0216ce561b

To be released in: https://github.com/aws/aws-for-fluent-bit/pull/356/files

**Comment by DrewZhang13** [comment]
New release is done: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.25.1
