### ISSUE TITLE
[Question] Is this not a recommended way of deploying Fluentbit in AWS?

### ISSUE THREAD

**Issue by q-leobrack** [aws/aws-for-fluent-bit#357]
Why is this chart not recommended in the cloud watch documentation? Is it not official/supported?

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs-FluentBit.html

**Comment by DrewZhang13** [comment]
Hi @q-leobrack, i may not understand the question. what do you mean for not recommended? Do you mean why fluent bit is not setup as the default/ recommended tool to send CloudWatch logs?

**Comment by q-leobrack** [comment]
Hi @DrewZhang13, sorry if my question was unclear.

When following the [AWS documentation guide to set up fluentbit](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs-FluentBit.html), specifically this section "To install Fluent Bit to send logs from containers to CloudWatch Logs" it recommends installing using kubernetes manifest files, rather than using this helm chart? Do you know why that is? I'd like to use the Helm chart, but I also do not want to diverge from the official AWS documentation.

**Comment by PettitWesley** [comment]
@q-leobrack I think both helm and the manifest files are recommended by AWS, and its just a matter of which you the customer prefer. I think the manifest files were noted in the AWS docs not as an exclusive option, but just because we felt they are the simplest/easiest option for beginners.

**Comment by q-leobrack** [comment]
@PettitWesley thanks for the clarification that the Helm chart is recommended by AWS.

We would like to use the Helm charts but were slightly concerned that they were not noted in the AWS docs we were following, so might not be supported going forward.
