### ISSUE TITLE
I want to change the log input path on ECS

### ISSUE THREAD

**Issue by zinho9** [aws/aws-for-fluent-bit#361]
I am trying to use this Dockerfile to get logs from ECS cluster to CloudWatch or S3 , Opensearch ..etc

I thought that this 
./var/lib/ecs/data/firelens/*/config/fluent.conf
file should be the config file for the output logs , because the output log group name is same as conf.

<img width="406" alt="스크린샷 2022-06-08 오후 6 01 02" src="https://user-images.githubusercontent.com/65962383/172577426-71338411-1f58-416b-90fe-e22cf9a00f7c.png">
<img width="751" alt="스크린샷 2022-06-08 오후 6 00 42" src="https://user-images.githubusercontent.com/65962383/172577453-89a7827e-8a93-47b5-a98f-9ec25e2b39fa.png">

I want to change the path before deploying the Docker Image.. so

./var/lib/ecs/data/firelens/*/config/fluent.conf 
I want to edit this file and dockerize the fluentbit image again. How can I do that?
I want to change the log collection path and make it docker image again.

**Comment by zhonghui12** [comment]
@zinho9 , could you please introduce more details here about current behavior and your expected behavior? Thanks. I am not sure which path you are referring to

**Comment by zinho9** [comment]
@zhonghui12 Hi! To be more specific, I'll make the java container run in ECS. At this time, the application log path will be **/var/lib/docker/overlay2/*/diff/home/svc-admin/logs/server.log**, so it seems to be necessary to modify the log input path in fluent.conf. I asked a question because I want to use the fluentbit image with the path that I want to modify, rather than the method of editing the conf file after the container is uploaded and the instance is running.

**Comment by zhonghui12** [comment]
Could you please send me the guidance of how you run fluent bit and your config file/Dockerfile? Sorry I am still kind of confused here. Also, not sure if you would like to link some file here but based on your description, I was not able to see any link here

**Comment by PettitWesley** [comment]
Some links for further reading which might help you understand FireLens and its design: 

* https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/ecs-log-collection
* https://aws.amazon.com/blogs/containers/under-the-hood-firelens-for-amazon-ecs-tasks/
* https://aws.amazon.com/blogs/containers/how-to-set-fluentd-and-fluent-bit-input-parameters-in-firelens/

**Comment by zinho9** [comment]
@zhonghui12 [https://aws.amazon.com/ko/blogs/korea/announcing-firelens-a-new-way-to-manage-container-logs/](url) 
Following this document, I deployed fluentbit and firelens on ECS. After deployment, two fluent-bit config files are created. One is the fluent-bit.conf file that exists in this repository, and the other is the conf value shown in the first picture I uploaded. I want to edit the fluent conf file I uploaded as a picture. It seems that the logs I want are being transmitted through the conf file, so I want to modify the INPUT and PATH of the conf. I want to create a fluentbit image that reflects the conf value I want to modify, not a method to modify it on the instance after deployment.

**Comment by zhonghui12** [comment]
@zinho9 so I think we might need to take a step back here. This path `./var/lib/ecs/data/firelens/*/config/fluent.conf` is the path where Firelens generates the final config file and you cannot change it. In other words, you are able to config the file/fluent bit but not to change the path. See more details about how FireLens works: https://aws.amazon.com/blogs/containers/under-the-hood-firelens-for-amazon-ecs-tasks/

In FireLens, you have two ways to config it. 1 - in `logConfiguration` like: https://github.com/aws-samples/amazon-ecs-firelens-examples/blob/mainline/examples/fluent-bit/cloudwatchlogs/task-definition.json#L28-L36. You can find more details here: https://github.com/aws-samples/amazon-ecs-firelens-examples#fluent-bit-examples. 2 - use import file like https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/config-file-type-file.
