### ISSUE TITLE
How does FireLens match `<service>-firelens` ?

### ISSUE THREAD

**Issue by JohnPreston** [aws/aws-for-fluent-bit#375]
ECS -> FireLens configuration enabled seem to allow to write FILTER that will then allow to do 

`Match <container>-firelens`

How / where is the `-firelens` added to the INPUT to match this ?

**Comment by zhonghui12** [comment]
That's how Firelens generates the config: https://github.com/aws-samples/amazon-ecs-firelens-under-the-hood/blob/mainline/generated-configs/fluent-bit/generated_by_firelens.conf#L37 and doc: https://github.com/aws-samples/amazon-ecs-firelens-under-the-hood/tree/mainline/generated-configs/fluent-bit

**Comment by JohnPreston** [comment]
@zhonghui12 
What I am asking is how does firelens do

"Finally, the output for the logs. Outputs created by FireLens will have the match pattern `{container name}-firelens*`."

**Comment by zhonghui12** [comment]
@JohnPreston 
FireLens will automatically tag the logs by `<container name>-firelens*`, please check our blog for more details: https://aws.amazon.com/blogs/containers/under-the-hood-firelens-for-amazon-ecs-tasks/. See section **Log Tagging in the generated config file**

**Comment by JohnPreston** [comment]
Thanks. But that's not what I am asking.
My question is both "why do you add `-firelens` ?" and "how do you add it ?".
From the generated configuration, there is nothing that would change the container tag name from `{container}` to `{container}-firelens` which means you are doing something different than native fluent-bit.
And that's what I am after. Because if I have FILTER in place with the `Match` to match `{container}-firelens` but use the OSS FluentBit image, then it does not match.

**Comment by PettitWesley** [comment]
@JohnPreston 

> From the generated configuration, there is nothing that would change the container tag name from {container} to {container}-firelens 

The tag is set by the Fluentd docker log driver: https://docs.docker.com/config/containers/logging/fluentd/

That log driver is used to send the stdout/stderr logs to Fluent Bit.

There's no special logic in the AWS Fluent Bit image vs upstream image (both images are fully open source), FireLens works with any Fluent Bit distro.

The reasoning behind the FireLens design is laid out here: https://aws.amazon.com/blogs/containers/under-the-hood-firelens-for-amazon-ecs-tasks/

**Comment by JohnPreston** [comment]
@PettitWesley so what you are saying is that firelens initializes the fluent log driver and you change the `tag`
``tag: specify a tag for fluentd message, which interprets some markup, ex {{.ID}}, {{.FullID}} or {{.Name}} docker.{{.ID}}``
and that's how the tag of containers goes from being `{container}` to `{container}-firelens`, for subsequent matches, right ?

If that's so then I would open a request so that, alike the [FirelensConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-firelensconfiguration.html) allows for option `disable-firelens-tag` so that the tags to run the `match` against allows to match `{container}` and not `{container}-firelens`.

Yes, one could already do such match with `Match {container}*` but for the sake of having better control, I think that'd be a good option.

**Comment by sparrc** [comment]
I believe this question was already answered here: https://github.com/aws/aws-for-fluent-bit/issues/375#issuecomment-1171749455, please feel free to reopen if there is any more information needed
