### ISSUE TITLE
Override default fluent-bit input forward port

### ISSUE THREAD

**Issue by 0x63lv** [aws/aws-for-fluent-bit#399]
FireLens listens on port `24224` by default. That appears to become an issue, if there is another container configured to bind to the same port within the same ECS Fargate task. So, is there a way to:
a) Override the default port to something other than `24224`?
b) Disable or remove this `[INPUT]` entirely?

We already build and use a custom docker image with an added custom configuration file, which is referenced in the ECS task definition. Essentially we're looking for the optimal way to not have a port conflict while still retaining ECS metadata in the log lines and use of our custom extra configuration.

### Configuration
```
{
    "name": "firelens_sidecar",
    "image": "our-custom/firelens-image:latest",
    "essential": true,
     ...
    "firelensConfiguration": {
      "type": "fluentbit",
      "options":{
        "enable-ecs-log-metadata":"true",
        "config-file-type": "file",
        "config-file-value": "/fluent-bit/etc/fluent-bit-custom.conf"
      }
    },
    "environment": [
      {
        "name": "VAR1",
        "value": "${var1}"
      },
      ...
    ],
    "logConfiguration": {
      "logDriver": "awslogs",
      "options": {
        "awslogs-group": "group",
        "awslogs-region": "zz-central-1",
        "awslogs-stream-prefix": "ecs"
      }
    }
  }
```

### Fluent Bit Log Output 

```
...
[2022/08/01 00:00:00] [ info] [input:forward:forward.2] listening on 127.0.0.1:24224
...
```

### Fluent Bit Version Info
`2.27.0`

###  Cluster Details
Sidecar on Fargate with `awsvpc` network mode.

**Comment by PettitWesley** [comment]
You want this I think: https://aws.amazon.com/blogs/containers/how-to-set-fluentd-and-fluent-bit-input-parameters-in-firelens/

You can override the generated config.

**Comment by 0x63lv** [comment]
Thanks @PettitWesley. Putting together that document with https://github.com/aws/aws-for-fluent-bit/issues/62#issuecomment-925702432 in another issue, we managed to get what we need.

**Comment by PettitWesley** [comment]
@0x63lv Please be aware of this new feature: https://github.com/aws/aws-for-fluent-bit/blob/mainline/use_cases/init-process-for-fluent-bit/README.md

It does things that are similar to what I see in the comment you linked.

**Comment by reachlin** [comment]
@PettitWesley one more question, will the init process merge my config into the one in the image? for example, if i add Mem_Buf_Limit to this forwarder, will it be merged into one or cause some conflicts?
```
[INPUT]
    Name forward
    unix_path /var/run/fluent.sock
    Mem_Buf_Limit 512MB
```
