### ISSUE TITLE
Aggregation

### ISSUE THREAD

**Issue by jasonrichardsmith** [aws/aws-for-fluent-bit#40]
I do not see documentation on this.

Does the Fluentbit plugins support aggregation like Fluentd does?
https://github.com/awslabs/aws-fluent-plugin-kinesis

**Comment by PettitWesley** [comment]
@jasonrichardsmith You mean support the KPL aggregated format in the Kinesis plugin?

We have an issue for that in the plugin repo: https://github.com/aws/amazon-kinesis-streams-for-fluent-bit/issues/16

**Comment by jasonrichardsmith** [comment]
Apologies. I will close this issue.  Thanks for the fast reply.
