### ISSUE TITLE
Missing timestamp

### ISSUE THREAD

**Issue by maggiedeuitch** [aws/aws-for-fluent-bit#43]
Hi there,
I'm new to Fluent Bit and logging, so I've been following this tutorial: https://aws.amazon.com/blogs/opensource/centralized-container-logging-fluent-bit/

I have the fluentd aggregator daemon running in my ECS cluster and it's collecting logs from an application container.

I've managed to send my logs to ES and Kibana, but I can't seem to figure out how to get a Timestamp field in there. Here are my configs:

Dockerfile
```
FROM amazon/aws-for-fluent-bit:latest
ADD fluent-bit.conf /fluent-bit/etc/
ADD parsers.conf /fluent-bit/etc/
```

fluent-bit.conf
```
[SERVICE]
    Parsers_File parsers.conf

[INPUT]
    Name forward
    unix_path /var/run/fluent.sock

[FILTER]
    Name parser
    Match **
    Parser docker
    Key_Name log

[OUTPUT]
    Name firehose
    Match **
    delivery_stream my-test-stream
    region ca-central-1
    time_key  time
    time_key_format %Y-%m-%dT%H:%M:%S%z
```

parsers.conf
```
[PARSER]
    Name docker
    Format json
    Time_Key time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep On
```
My log still ends up as one string with no timestamp field. I'm not quite sure what I've misconfigured. I've also tried the nginx parser as I have nginx logs, but that doesn't work either.

```
    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
``` 
Any idea what might be missing? 
Thanks

**Comment by sonofachamp** [comment]
Can you share the full Fluent Bit configuration you're using when trying to apply the `nginx` parser?

I had a very similar pain and created [this repo](https://github.com/sonofachamp/elkstack) with a basic setup for Fluent Bit + nginx + ELK stack. I think this will give you second-resolution `@timestamp` values in Kibana by default, but you can override the nginx configuration to include millisecond resolution with the `$msec` variable.

**Comment by PettitWesley** [comment]
@maggiedeuitch This doesn't make sense to me...

```
[OUTPUT]
    Name firehose
    Match **
    delivery_stream my-test-stream
    region ca-central-1
    time_key  time
    time_key_format %Y-%m-%dT%H:%M:%S%z
```

The `time_key` and `time_key_format` configs should ensure you get a timestamp... the firehose plugin will insert a timestamp for you with that format. If it isn't then we have a bug...

This makes me wonder if somehow Kibana is discarding the timestamp or something.

**Comment by kamilhristov** [comment]
Random thought, why bother parsing the time key and setting **Time_Keep** when time is also set by the output plugin ?

```
    Time_Key time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep On
```

And could this be causing issues ? Having the time key already defined before the output 🤔

**Comment by sonofachamp** [comment]
It sounds like you've got everything working now, so I'll close this. Please reach out or re-open if you have anything else we can help with!
