### ISSUE TITLE
Docs: Note which build targets require AWS credentials/fail fast if not found

### ISSUE THREAD

**Issue by ShelbyZ** [aws/aws-for-fluent-bit#439]
### Describe the question/issue

The primary README provides direction on using the `makefile` to build targets for running integration tests. These will fail due to requiring access to AWS credentials (file or ENV variables):

```
WARN[0000] The "AWS_ACCESS_KEY_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "AWS_SECRET_ACCESS_KEY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "AWS_SESSION_TOKEN" variable is not set. Defaulting to a blank string. 
```

It may make sense to update documentation to clearly indicate what is required for each integration test target and update any related scripts (integ.sh, etc) to fail fast if requirements are not met.

### Configuration

N/A

### Fluent Bit Log Output 

To run integration tests it require a series of environment variables to be set:
```
Attaching to test_kinesis-validate-s3-1
test_kinesis-validate-s3-1  | [TEST FAILURE] Bucket name required. Set the value for environment variable- S3_BUCKET_NAME
test_kinesis-validate-s3-1 exited with code 1
Aborting on container exit...
[+] Running 1/0
 ⠿ Container test_kinesis-validate-s3-1  Stopped                                                                  0.0s
```

A rough list looks like (pulled from docker compose files):
- KINESIS_STREAM
- S3_BUCKET_NAME
- LOG_GROUP_NAME
- FIREHOSE_STREAM

### Fluent Bit Version Info

N/A

###  Cluster Details

N/A

### Application Details

N/A

### Steps to reproduce issue

Run `make integ-dev`

### Related Issues

N/A

**Comment by sparrc** [comment]
fixed by https://github.com/aws/aws-for-fluent-bit/pull/866
