### ISSUE TITLE
arm64 build needed

### ISSUE THREAD

**Issue by otterley** [aws/aws-for-fluent-bit#44]
Now that ECR supports multi-arch images, and EC2 instance types using Graviton2 processors have reached GA, it's time for us to build dual x86-64/arm64 images using multi-arch builds.

**Comment by JeffUnderhill** [comment]
The upstream Fluent Bit project have added Arm64v8 packages for most Linux distributions as a supported platform - [See](https://docs.fluentbit.io/manual/installation/supported-platforms). Are there any other component pieces needed for Arm64 support at this time?

**Comment by otterley** [comment]
This GitHub project produces the Docker image that includes not only the upstream software, but also the AWS-specific plugins it uses (CloudWatch Logs, Kinesis Streams, etc.). Those plugins have to be compiled for Arm64v8, too.

**Comment by lubingfeng** [comment]
This sounds like a feature request rather than a defect to me.

**Comment by autarchprinceps** [comment]
This is particularly important on EKS. This runs as a daemonset to export container logs to CloudWatch Logs, or other targets. If every node runs an instance, but it's not supported on ARM, that means ARM instances aren't properly supported as EKS nodes, not even in a mixed setup with x86 nodes for other non supported software.

**Comment by lubingfeng** [comment]
AWS fluent bit ARM 64 support is coming soon.

**Comment by zhonghui12** [comment]
Hi @otterley @JeffUnderhill @autarchprinceps , ARM64 is included in our recent release. Please check here: https://github.com/aws/aws-for-fluent-bit/blob/mainline/CHANGELOG.md.

Thanks. This issue will be closed.
