### ISSUE TITLE
Default "log" key is not replaced by custom key.

### ISSUE THREAD

**Issue by yogeshjoshi** [aws/aws-for-fluent-bit#50]
I'm trying to change the default log key of fluent-bit container, but seems i'm not able to get it.

**Docker file :**
`FROM amazon/aws-for-fluent-bit:latest
ADD fluent-bit.conf /
ADD fluent-bit.conf /fluent-bit/etc/
ADD parsers.conf /
ADD parsers.conf /fluent-bit/etc/
USER root`

**FluentBit conf (Used Modigy Plugin to change key)**
[SERVICE]
    Parsers_File    /parsers.conf
    Log_Level       debug

[INPUT]
    Name        forward
    Listen      0.0.0.0
    Port        24224

[INPUT]
    Name    tail
    Path    /opt/akoshalogs/*.log

[FILTER]
    Name    modify
    Match   *
    Rename log message

[OUTPUT]
    Name    stdout
    Match   *

**Parsers conf file** 
[PARSER]
    Name    json
    Format  json

How I'm running -- 
```docker run -it fluentbit bash```

```
bash-4.2# mkdir /opt/akoshalogs/
bash-4.2# echo  "{\"key\": \"$(date)\"}" >> /opt/akoshalogs/filename.log
bash-4.3#  cd fluent-bit/bin/
bash-4.3# ./fluent-bit \
  -i tail \
  -p path=/opt/akoshalogs/filename.log \
  -t testcase \
  -o stdout
```
Output Still showing -` [0] testcase: [1593853555.324835600, {"log"=>"{"key": "Sat Jul  4 09:05:42 UTC 2020"}"}]
`
 @PettitWesley Could you help on this.

**Comment by PettitWesley** [comment]
@yogeshjoshi 

> bash-4.3# ./fluent-bit \
  -i tail \
  -p path=/opt/akoshalogs/filename.log \
  -t testcase \
  -o stdout


If you run Fluent Bit with that command, then your config file is not being used and the modify filter will not be used.

The entrypoint for AWS for Fluent Bit is here: https://github.com/aws/aws-for-fluent-bit/blob/master/entrypoint.sh#L3

If you want to invoke the Fluent Bit binary direct'y, make sure to use the config file option `-c`:

```
/fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
```

**Comment by yogeshjoshi** [comment]
@PettitWesley Just last one doubt, If we want to build the "custom-image" and pushed into ECR and then want to use as Side-Car what would be the Docker file, do we have to add entrypoint.sh in docker image?
PS : we don't want to use firelens "file" path option for conf file and "s3" option we can't use as we are in fargate.

**Comment by PettitWesley** [comment]
You can have a very simple Dockerfile for adding an extra config with FireLens:

```
FROM amazon/aws-for-fluent-bit:latest
ADD extra.conf /extra.conf
```

Please look at and understand the Task Definition and example here; it is for a different use case, but the overall solution is similar to what you need: https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/parse-json

> PS : we don't want to use firelens "file" path option for conf file and "s3" option we can't use as we are in fargate

I understand; S3 is more convenient than the custom image with file option. I am sorry s3 support has not yet come to Fargate; unfortunately I can not say when it will.

**Comment by yogeshjoshi** [comment]
Thanks for Clarification, Closing the Issue.
