### ISSUE TITLE
Extra User Agent Type

### ISSUE THREAD

**Issue by matthewfala** [aws/aws-for-fluent-bit#503]
There are some compile time errors that don't seem to affect runtime as far as I'm aware. The following errors appear at compile time
```
/src/fluent-bit/src/aws/flb_aws_util.c:244:29: warning: incompatible pointer types passing 'flb_sds_t *' (aka 'char **') to parameter of type 'flb_sds_t' (aka 'char *'); dereference with * [-Wincompatible-pointer-types]
            flb_sds_destroy(aws_client->extra_user_agent);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                            *
/src/fluent-bit/include/fluent-bit/flb_sds.h:109:32: note: passing argument to parameter 's' here
void flb_sds_destroy(flb_sds_t s);
                               ^
/src/fluent-bit/src/aws/flb_aws_util.c:374:38: warning: incompatible pointer types assigning to 'flb_sds_t *' (aka 'char **') from 'flb_sds_t' (aka 'char *'); take the address with & [-Wincompatible-pointer-types]
        aws_client->extra_user_agent = tmp;
                                     ^ ~~~
                                       &
/src/fluent-bit/src/aws/flb_aws_util.c:380:20: warning: incompatible pointer types passing 'flb_sds_t *' (aka 'char **') to parameter of type 'const char *'; dereference with * [-Wincompatible-pointer-types]
    if (strcasecmp(aws_client->extra_user_agent, AWS_USER_AGENT_NONE) == 0) {
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   *
```

This is because extra_user_agent defined here:
https://github.com/fluent/fluent-bit/blob/baa91a5c7006a1c30637e712ae4fde694f013080/include/fluent-bit/flb_aws_util.h#L82

is of type flb_sds_t*, meanwhile it is being set to a flb_sds_t here:
https://github.com/fluent/fluent-bit/blob/1a9858039a8bad025cc012a7a0835bc2de5ada2f/src/aws/flb_aws_util.c#L374

Note, everywhere it is used, it is used as a flb_sds_t which is actually really just a wrapped char*:
https://github.com/fluent/fluent-bit/blob/eceeb5fe7b550a6a6069b79850b635f985f5ac0a/include/fluent-bit/flb_sds.h#L36

Needs more checking, but probably it is safe to change:
https://github.com/fluent/fluent-bit/blob/baa91a5c7006a1c30637e712ae4fde694f013080/include/fluent-bit/flb_aws_util.h#L82

```
    flb_sds_t *extra_user_agent;
```

to:

```
    flb_sds_t extra_user_agent;
```

**Comment by matthewfala** [comment]
PR to resolve issue: https://github.com/fluent/fluent-bit/pull/6584#pullrequestreview-1223684477

**Comment by PettitWesley** [comment]
https://github.com/fluent/fluent-bit/pull/6585
