### ISSUE TITLE
Support New CloudWatch Logs Sequence Token Deprecation and Ingestion Limit Removal

### ISSUE THREAD

**Issue by PettitWesley** [aws/aws-for-fluent-bit#526]
We are working on removing sequence token tracking which will enable higher throughput: https://github.com/fluent/fluent-bit/pull/6741

We also need to update our load tests to test higher throughput: https://github.com/fluent/fluent-bit/pull/6741#issuecomment-1405726115

When this is released, it means you can now use multi-workers with cloudwatch_logs output:

```
[OUTPUT]
    Name cloudwatch_logs
    Match   *
    region us-east-1
    log_group_name fluent-bit-cloudwatch
    log_stream_prefix from-fluent-bit-
    auto_create_group On
    workers 5
```

UPDATE: This is released: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.32.0

**Comment by matthewfala** [comment]
Here is the Sequence Token Deprecation ingestion limit removal pr:
https://github.com/fluent/fluent-bit/pull/6741/files

Testing and code review is in progress
Here are the branches being used for testing:
https://github.com/fala-aws/aws-for-fluent-bit/tree/std-control
https://github.com/fala-aws/aws-for-fluent-bit/tree/std-patch-1-workers
https://github.com/fala-aws/aws-for-fluent-bit/tree/std-patch-20-workers

**Comment by matthewfala** [comment]
Here's the updated PR to master: https://github.com/fluent/fluent-bit/pull/7973
And it's corresponding aws-for-fluent-bit release: https://github.com/aws/aws-for-fluent-bit/pull/733
