### ISSUE TITLE
[init process integ test] - an example config file's name need to be changed

### ISSUE THREAD

**Issue by Galaoaoa** [aws/aws-for-fluent-bit#564]
The name of [dummy-Input.conf](https://github.com/aws/aws-for-fluent-bit/blob/mainline/integ/test_init/config_files_for_test/dummy-Input.conf) need to be changed to `dummy-input.conf`, to kept consistent with the content in [integ_test_stack.py](https://github.com/aws/aws-for-fluent-bit/blob/mainline/integ/test_init/integ_test/integ_test/integ_test_stack.py).

**Comment by PettitWesley** [comment]
Thanks! @Claych fixed this.
