### ISSUE TITLE
2.31.7 container failing Sysdig Scans.

### ISSUE THREAD

**Issue by ronkara** [aws/aws-for-fluent-bit#623]
### Describe the question/issue
We are on the latest version of AWS fluentbit 2.31.7 and currently scans are failing on 4 libraries based on versions.  Can we find out when the latest version of the following libraries will be updated as I have to report POAMs for these vulns on a monthly basis:
libdb 5.3.21-24.amzn2.0.4
libdb-utils 5.3.21-24.amzn2.0.4
vim-data 9.0.1314-1.amzn2.0.1
vim-minimal 9.0.1314-1.amzn2.0.1
python 2.7.18-1amzn2.0.6
python-libs 2.7.18-1amzn2.0.6
nss 3.79.0-4.amzn2.0.1
nss-sysinit 3.79.0-4.amzn2.0.1
nss-tools 3.79.0-4.amzn2.0.1
vim-data 9.0.1367-1.amzn2.0.1
vim-minimal 9.0.1367-1.amzn2.0.1
cpio 2.12-11.amzn2
openssl11-devel 1.1.1g-12.amzn2.0.13
openssl11-libs 1.1.1g-12.amzn2.0.13
curl 7.88.0-1.amzn2.0.1
libcurl 7.88.0-1.amzn2.0.1
libxml2 2.9.1-6.amzn2.5.7

First time that I have made a request so please understand that I did not mean to miss anything.  We must report vulns to our security manager on a monthly basis and the list of files have severities requiring remediation within specific timeframes.

### Configuration
2.31.7 running in AWS EKS

### Fluent Bit Version Info
2.31.7

### Steps to reproduce issue
Use 2.31.7 running in AWS EKS and scan it with Sysdig container scanner.

**Comment by PettitWesley** [comment]
Per our patching policy we can put out a new patch release if we reproduce the finding: https://github.com/aws/aws-for-fluent-bit#compliance-and-patching

**Comment by PettitWesley** [comment]
We're working on a re-build CVE patch release: https://github.com/aws/aws-for-fluent-bit/pull/627

**Comment by PettitWesley** [comment]
2.31.8 is out
