### ISSUE TITLE
Switch to native CloudWatch Log plugin

### ISSUE THREAD

**Issue by david7482** [aws/aws-for-fluent-bit#65]
Because [FluentBit 1.5](https://fluentbit.io/announcements/v1.5.0/) has the native CloudWatch Log plugin, any plan to switch to it so we could also reduce the image size?

Thanks

**Comment by sonofachamp** [comment]
It's a good suggestion, but I don't know that the Go plugin would be removed from this distribution any time soon.

From a functionality standpoint, you should be able to leverage either Cloudwatch plugin (Go or native C) via the `aws-for-fluent-bit` image in `v2.4.0` or later as that is when we included Fluent Bit `v1.5`.

From an image size standpoint, if you're using the native Cloudwatch plugin and don't depend on any of the other plugins specific to the `aws-for-fluent-bit` image then you can use the `fluent/fluent-bit` image which is significantly smaller:

#### `fluent/fluent-bit:latest`

```
→ docker image ls fluent/fluent-bit:latest
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
fluent/fluent-bit   latest              f70cb7df328c        11 days ago         77.4MB
```

#### `amazon/aws-for-fluent-bit:latest`
```
→ docker image ls amazon/aws-for-fluent-bit:latest
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
amazon/aws-for-fluent-bit   latest              770704bd79d8        5 days ago          576MB
```

**Comment by sonofachamp** [comment]
Related: #17

**Comment by sonofachamp** [comment]
Closing in favor of #17.
