### ISSUE TITLE
eks-charts: log_retention_days does not seem to work 

### ISSUE THREAD

**Issue by RiskyAdventure** [aws/aws-for-fluent-bit#651]
### Describe the question/issue
In testing both the cloudwatch and cloudwatchlogs modules on both the aws-for-fluent-bit and the upstream helm charts we could not get the log group to create with a retention setting. We would like to see this fixed and the default changed to 30 days.

### Configuration

logRetentionDays: 30

### Fluent Bit Version Info

2.28.4

###  Cluster Details

Two different clusters done by two different engineers.

**Comment by PettitWesley** [comment]
The feature seems to be working fine in the actual Fluent Bit code when I test it directly:

```
[INPUT]
    Name dummy
    Tag dummy

[OUTPUT]
    Name cloudwatch
    Match   *
    region us-east-1
    log_group_name log_retention_days
    log_stream_prefix from-fluent-bit-
    auto_create_group true
    log_retention_days 30
```

```
INFO[0001] [cloudwatch 0] Created log group log_retention_days
INFO[0001] [cloudwatch 0] Set retention policy on log group log_retention_days to 30d
```


```
[OUTPUT]
    Name cloudwatch_logs
    Match   *
    region us-east-1
    log_group_name log_retention_days
    log_stream_prefix from-fluent-bit-
    auto_create_group true
    log_retention_days 1
```

```
[2023/05/15 20:56:24] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Created log group log_retention_days
[2023/05/15 20:56:24] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Setting retention policy on log group log_retention_days to 1d
[2023/05/15 20:56:24] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Set retention policy to 1
```

**Comment by PettitWesley** [comment]
The chart template looks correct to me: https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/templates/configmap.yaml#L133

**Comment by PettitWesley** [comment]
@RiskyAdventure Can you share your chart values that you tested with? 

When you tested, did you have https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html permissions for FLB? Did it show anything in its own log output?

**Comment by RiskyAdventure** [comment]
Confirmed that PutRetentionPolicy is not in the EKSCTL default CloudWatchAgentServerPolicy, thanks for the help!
