### ISSUE TITLE
Feature Request - Change to multiline.parser with containerd CRI support

### ISSUE THREAD

**Issue by RiskyAdventure** [aws/aws-for-fluent-bit#652]
### Describe the question/issue
Request adding support for containerd by moving to the new multiline parser with the CRI option. 

### Configuration

multiline.parser    docker, cri

### Fluent Bit Version Info

2.28.4

**Comment by PettitWesley** [comment]
@RiskyAdventure This one is specific to the helm chart, please open it against that repo: https://github.com/aws/eks-charts
