### ISSUE TITLE
EKS Fargate sidecar logging - collect logs in app volume mount

### ISSUE THREAD

**Issue by somrajroy** [aws/aws-for-fluent-bit#656]
### Describe the question/issue
I have 2 pods running in my AWS EKS fargate Cluster and they store logs to a specific folder within the container. I implemented AWS built-in log router based on Fluent Bit for Amazon EKS on Fargate (as mentioned in link [https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html](https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.aws.amazon.com%2Feks%2Flatest%2Fuserguide%2Ffargate-logging.html&data=05%7C01%7Csomraj.roy%40lntinfotech.com%7C1679389bedfc494e65c908db578668af%7C02aa9fc118bc4798a020e01c854dd434%7C0%7C0%7C638200007025105701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xjO01chpikp%2Fu92RCfjkFAYbeXqYljyUxZh7RgMVjxQ%3D&reserved=0)). How do I ensure the FluentBit picks up logs stored in that specific folder and sends them to CloudWatch along with normal logs collected by Fluentbit.

Secondly, please let me know what is the default path and folder from where FluentBit picks up log and sends to CloudWatch.

The INPUT section of FluentBit config is managed by AWS as below. Kindly confirm if this is correct and still valid.

[INPUT]
    Name tail
    DB /var/log/flb_kube.db
    Mem_Buf_Limit 10MB
    Path /var/log/containers/*.log
    Read_From_Head On
    Refresh_Interval 10
    Rotate_Wait 30
    Skip_Long_Lines On
    Tag kube.*

@PettitWesley

**Comment by PettitWesley** [comment]
> they store logs to a specific folder within the container.  How do I ensure the FluentBit picks up logs stored in that specific folder and sends them to CloudWatch along with normal logs collected by Fluentbit.

The built-in Fluent Bit is really only for your pod stdout logs: https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html

You can not add custom inputs for it. 

If you also need to collect your own log files in your own container, then you should separately deploy Fluent Bit as sidecar in your pod and create a volume mount for it in your app container to read those log files.

**Comment by somrajroy** [comment]
please let me know what is the default path and folder from where FluentBit picks up log and sends to CloudWatch. There must be a folder from where Fluentbit picks up the log. Else let me know to send (or intrument) for pod stdout logs.

**Comment by PettitWesley** [comment]
The built-in EKS Fargate Fluent BIt can only collect stdout & stderr logs. Please follow a guide for your application language or framework to enable stdout and stderr logging.

**Comment by PettitWesley** [comment]
I forgot we had a blog on this: https://aws.amazon.com/blogs/containers/how-to-capture-application-logs-when-using-amazon-eks-on-aws-fargate/

**Comment by somrajroy** [comment]
@PettitWesley  : I found a solution for this. These 2 commands will solve your problem - java -jar /java/xyz-java-app.jar | tee /var/log/javalogs/sbapp.log & java -jar /java/xyz-java-app.jar 2>&1 | tee /var/log/javalogs/sbapp.log.

This will send the logs from custom specific folder and save it to a file plus send it to pod stdout. 

Kindly update the documentation link you shared earlier - https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html. Have a nice day...Cheers.

**Comment by somrajroy** [comment]
@PettitWesley : I found a solution for this. It is the "tee" command. You can send logs to stdout plus custom folders/file(s). It works.

Kindly update the documentation link you shared earlier - https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html. Have a nice day...Cheers.
