### ISSUE TITLE
FluentBit exits on container start [config issue]

### ISSUE THREAD

**Issue by dharshanrg** [aws/aws-for-fluent-bit#659]
Hi,

I am trying to use AWS FluentBit to push logs to Cloudwatch (and other providers down the line). The fluentbit process fails on startup complaining of an issue with plugins.

2023-05-19T18:07:58.300+00:00 | Fluent Bit v1.9.9
-- | --
  | 2023-05-19T18:07:58.300+00:00 | * Copyright (C) 2015-2022 The Fluent Bit Authors
  | 2023-05-19T18:07:58.300+00:00 | * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
  | 2023-05-19T18:07:58.300+00:00 | * https://fluentbit.io
  | 2023-05-19T18:07:58.304+00:00 | [2023/05/19 18:07:58] [error] [config] section 'configuration' tried to instance a plugin name that don't exists
  | 2023-05-19T18:07:58.305+00:00 | [2023/05/19 18:07:58] [error] configuration file contains errors, aborting.
  | 2023-05-19T18:07:58.435+00:00 | AWS for Fluent Bit Container Image Version 2.28.5

Here is the ECS configuration that  I am using. 
{
    "taskDefinitionArn": "arn:aws:ecs:us-west-2:755468731030:task-definition/logrouter:3",
    "containerDefinitions": [
        {
            "name": "logrouter",
            "image": "906394416424.dkr.ecr.us-west-2.amazonaws.com/aws-for-fluent-bit:stable",
            "cpu": 0,
            "portMappings": [],
            "essential": true,
            "environment": [
                {
                    "name": "FLB_LOG_LEVEL",
                    "value": "debug"
                }
            ],
            "mountPoints": [],
            "volumesFrom": [],
            "user": "0",
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "/ecs/logrouter",
                    "awslogs-create-group": "true",
                    "awslogs-region": "us-west-2",
                    "awslogs-stream-prefix": "ecs"
                }
            },
            "firelensConfiguration": {
                "type": "fluentbit"
            }
        },
        {
            "name": "logdriver",
            "image": "alpine:3.13",
            "cpu": 0,
            "portMappings": [],
            "essential": true,
            "entryPoint": [
                "sh",
                "-c"
            ],
            "command": [
                "/bin/sh -c \"while true; do sleep 15 ;echo hello_world; done\""
            ],
            "environment": [],
            "mountPoints": [],
            "volumesFrom": [],
            "logConfiguration": {
                "logDriver": "awsfirelens",
                "options": {
                    "awslogs-group": "/ecs/CentralizedConfiguration",
                    "log_stream_name": "$(ecs_task_id)",
                    "awslogs-region": "us-west-2",
                    "awslogs-create-group": "true",
                    "Name": "configuration",
                    "awslogs-stream-prefix": "ecs-firelens",
                    "retry_limit": "2"
                }
            }
        }
    ],
    "family": "logrouter",
    "executionRoleArn": "arn:aws:iam::755468731030:role/ecsTaskExecutionRole",
    "networkMode": "awsvpc",
    "revision": 3,
    "volumes": [],
    "status": "ACTIVE",
    "requiresAttributes": [
        {
            "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
        },
        {
            "name": "ecs.capability.execution-role-awslogs"
        },
        {
            "name": "com.amazonaws.ecs.capability.ecr-auth"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
        },
        {
            "name": "ecs.capability.firelens.fluentbit"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.17"
        },
        {
            "name": "com.amazonaws.ecs.capability.logging-driver.awsfirelens"
        },
        {
            "name": "ecs.capability.execution-role-ecr-pull"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
        },
        {
            "name": "ecs.capability.task-eni"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.29"
        }
    ],
    "placementConstraints": [],
    "compatibilities": [
        "EC2",
        "FARGATE"
    ],
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "cpu": "256",
    "memory": "512",
    "runtimePlatform": {
        "cpuArchitecture": "X86_64",
        "operatingSystemFamily": "LINUX"
    },
    "registeredAt": "2023-05-19T18:03:48.870Z",
    "registeredBy": "arn:aws:iam::755468731030:root",
    "tags": []
}

How can I proceed to debug this? The fluentbit config file was generated by AWS.

**Comment by PettitWesley** [comment]
> "logConfiguration": {
"logDriver": "awsfirelens",
"options": {
"awslogs-group": "/ecs/CentralizedConfiguration",
"log_stream_name": "$(ecs_task_id)",
"awslogs-region": "us-west-2",
"awslogs-create-group": "true",
"Name": "configuration",
"awslogs-stream-prefix": "ecs-firelens",
"retry_limit": "2"
}


This is not valid Fluent Bit configuration. Please review:
- https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/cloudwatchlogs
- https://aws.amazon.com/blogs/containers/under-the-hood-firelens-for-amazon-ecs-tasks/

> "logDriver": "awslogs",
"options": {
"awslogs-group": "/ecs/logrouter",

I see you have enabled awslogs driver for Fluent Bit, which means you can check cloudwatch for its output.

**Comment by dharshanrg** [comment]
Hi,

Thank you for the input. I have updated the awsfirelens configuration as per your instructions. However the issue is with the fluent-bit container which is using the awslogs driver.  Here is what I see in the cloudwatch logs. How do I trace out the full fluent-bit config file that aws is generating?

 2023-05-30T18:03:02.350+00:00	Fluent Bit v1.9.9

2023-05-30T18:03:02.350+00:00	* Copyright (C) 2015-2022 The Fluent Bit Authors

2023-05-30T18:03:02.350+00:00	* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd

2023-05-30T18:03:02.350+00:00	* https://fluentbit.io

2023-05-30T18:03:02.372+00:00	[2023/05/30 18:03:02] [error] [config] section 'configuration' tried to instance a plugin name that don't exists

2023-05-30T18:03:02.372+00:00	[2023/05/30 18:03:02] [error] configuration file contains errors, aborting.

2023-05-30T18:03:02.472+00:00	AWS for Fluent Bit Container Image Version 2.28.5

Also here is the updated task definition I am using
{
    "taskDefinitionArn": "arn:aws:ecs:us-west-2:755468731030:task-definition/logrouter:4",
    "containerDefinitions": [
        {
            "name": "logrouter",
            "image": "906394416424.dkr.ecr.us-west-2.amazonaws.com/aws-for-fluent-bit:stable",
            "cpu": 0,
            "portMappings": [],
            "essential": true,
            "environment": [
                {
                    "name": "FLB_LOG_LEVEL",
                    "value": "debug"
                }
            ],
            "mountPoints": [],
            "volumesFrom": [],
            "user": "0",
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-create-group": "true",
                    "awslogs-group": "/ecs/logrouter",
                    "awslogs-region": "us-west-2",
                    "awslogs-stream-prefix": "ecs"
                }
            },
            "firelensConfiguration": {
                "type": "fluentbit"
            }
        },
        {
            "name": "logdriver",
            "image": "alpine:3.13",
            "cpu": 0,
            "portMappings": [],
            "essential": true,
            "entryPoint": [
                "sh",
                "-c"
            ],
            "command": [
                "/bin/sh -c \"while true; do sleep 15 ;echo hello_world; done\""
            ],
            "environment": [],
            "mountPoints": [],
            "volumesFrom": [],
            "logConfiguration": {
                "logDriver": "awsfirelens",
                "options": {
                    "Name": "configuration",
                    "auto_create_group": "true",
                    "log_group_name": "/aws/ecs/containerinsights/$(ecs_cluster)/application",
                    "log_stream_name": "$(ecs_task_id)",
                    "region": "us-west-2",
                    "retry_limit": "2"
                }
            }
        }
    ],
    "family": "logrouter",
    "executionRoleArn": "arn:aws:iam::755468731030:role/ecsTaskExecutionRole",
    "networkMode": "awsvpc",
    "revision": 4,
    "volumes": [],
    "status": "ACTIVE",
    "requiresAttributes": [
        {
            "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
        },
        {
            "name": "ecs.capability.execution-role-awslogs"
        },
        {
            "name": "com.amazonaws.ecs.capability.ecr-auth"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
        },
        {
            "name": "ecs.capability.firelens.fluentbit"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.17"
        },
        {
            "name": "com.amazonaws.ecs.capability.logging-driver.awsfirelens"
        },
        {
            "name": "ecs.capability.execution-role-ecr-pull"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
        },
        {
            "name": "ecs.capability.task-eni"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.29"
        }
    ],
    "placementConstraints": [],
    "compatibilities": [
        "EC2",
        "FARGATE"
    ],
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "cpu": "256",
    "memory": "512",
    "runtimePlatform": {
        "cpuArchitecture": "X86_64",
        "operatingSystemFamily": "LINUX"
    },
    "registeredAt": "2023-05-30T18:07:29.353Z",
    "registeredBy": "arn:aws:iam::755468731030:root",
    "tags": []
}

**Comment by PettitWesley** [comment]
> 2023-05-30T18:03:02.372+00:00 [2023/05/30 18:03:02] [error] [config] section 'configuration' tried to instance a plugin name that don't exists

> 2023-05-30T18:03:02.372+00:00 [2023/05/30 18:03:02] [error] configuration file contains errors, aborting.

You specified `Name` as `configuration` in your logConfiguration in the task def, this is the problem. 

Please read all of the below on using FireLens + on how it generates the Fluent Bit config. 

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html

https://github.com/aws/aws-for-fluent-bit/blob/mainline/troubleshooting/debugging.md#tutorial-replicate-an-ecs-firelens-task-setup-locally

https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/cloudwatchlogs
https://aws.amazon.com/blogs/containers/under-the-hood-firelens-for-amazon-ecs-tasks/

**Comment by dharshanrg** [comment]
Thank you for your tips. I was able to resolve the configuration and get it running.
