### ISSUE TITLE
Android platform support?

### ISSUE THREAD

**Issue by abdelmadjid-dev** [aws/aws-for-fluent-bit#669]
any info or guide to implement fluentbit on android devices? for system resource monitoring and logs collection of some specific apps (private apps that belong to developers) ?

related stackoverflow question [Log Collection From Android Devices](https://stackoverflow.com/questions/48854170/log-collection-from-android-devices)

any insight is deeply appreciated

**Comment by PettitWesley** [comment]
I found this upstream issue, so someone else was trying android dev: https://github.com/fluent/fluent-bit/issues/5466

Fluent Bit builds on arm and is designed to work on embedded systems... so it should work on android. 

I'm not personally aware of any resources for working with that though. 

Try opening this same issue upstream.

**Comment by PettitWesley** [comment]
This repo is specifically for AWS issues, and AWS does not support FLB on Android, so I am closing this issue. Please open one here: https://github.com/fluent/fluent-bit/issues
