### ISSUE TITLE
*_PLUGIN_BRANCH vars don't do anything

### ISSUE THREAD

**Issue by rs-garrick** [aws/aws-for-fluent-bit#67]
Hi all,

I'm trying to test out Zackwine's KPL aggregation branch from https://github.com/zackwine/amazon-kinesis-streams-for-fluent-bit. The bottom of the aws-for-fluent-bit README mentions setting $KINESIS_PLUGIN_BRANCH, but near as I can tell, the *_PLUGIN_BRANCH vars aren't used anywhere. The Docker.plugins reads *_PLUGIN_TAG. Of course, there are no tags available for these dev forks.

Am I missing something?

**Comment by PettitWesley** [comment]
Uhh... I am not sure, but I think they are still used and set properly in Makefile: https://github.com/aws/aws-for-fluent-bit/blob/master/Makefile#L41

**Comment by rs-garrick** [comment]
But then look in Dockerfile.plugins. $KINESIS_PLUGIN_BRANCH isn't read by anything.

**Comment by PettitWesley** [comment]
@rs-garrick You're right...

I am not sure of the best way to fix it.

**Comment by PettitWesley** [comment]
I think may be we should just have 2 Dockerfiles, one for release, one for test. Since Dockerfiles don't support any sort of easy conditional logic.

**Comment by PettitWesley** [comment]
@rs-garrick If you want to test out the new aggregation format support- just build this repo from an older commit- https://github.com/aws/aws-for-fluent-bit/commit/66c256fecdbfc251e333d8e2a168202a44b627f6

**Comment by rs-garrick** [comment]
Is this too goofy? I can submit a complete PR if you like.

 RUN git clone $KINESIS_PLUGIN_CLONE_URL /kinesis-streams
 WORKDIR /kinesis-streams
-RUN git fetch --all --tags && git checkout tags/$KINESIS_PLUGIN_TAG -b $KINESIS_PLUGIN_TAG && git describe --tags
+RUN if [ -n "$KINESIS_PLUGIN_BRANCH" ];then git fetch --all && git checkout $KINESIS_PLUGIN_BRANCH && git remote -v;fi
+RUN if [ -z "$KINESIS_PLUGIN_BRANCH" ];then git fetch --all --tags && git checkout tags/$KINESIS_PLUGIN_TAG -b $KINESIS_PLUGIN_TAG && git describe --tags;fi

**Comment by PettitWesley** [comment]
@rs-garrick I'm fine with anything that works. If you can get this working, put up a PR.

**Comment by PettitWesley** [comment]
@rs-garrick Merged your PR, thanks!
