### ISSUE TITLE
InvalidParameterException: Log event too large

### ISSUE THREAD

**Issue by albertschwarzkopf** [aws/aws-for-fluent-bit#68]
Hi,

we are using this tool in K8s as Daemonset and get the following error sometimes (it depends on which node the pod is running and which other pods are running on this node):

`time="2020-08-26T08:24:17Z" level=error msg="[cloudwatch 0] InvalidParameterException: Log event too large: 635616 bytes exceeds limit of 262144\n\tstatus code: 400, request id: 9d79f780-3842-4438-a73d-dc6cc54864c8\n" [2020/08/26 08:24:17] [ warn] [engine] chunk '1-1598430244.412167060.flb' cannot be retried: task_id=2, input=tail .0 > output=cloudwatch.0`

So I know that there is this limit in AWS CW: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/CalculatePutEventsEntrySize.html

Is it possible to handle this issue (e.g. truncation, ...)?

Best regards,
Albert

**Comment by hossain-rayhan** [comment]
Hi @albertschwarzkopf , I believe this issue is more related to [amazon-cloudwatch-logs-for-fluent-bit](https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit) plugin. You were right earlier. Let's close this one and reopen the previous one in our cloudwatch plugin repo.
