### ISSUE TITLE
App version not reported anymore for Helm chart (since 0.1.26)

### ISSUE THREAD

**Issue by Constantin07** [aws/aws-for-fluent-bit#694]
### Describe the question/issue

Looks like App version is not reported anymore in the latest Helm chart version - just `stable` shown.
What version exactly the `stable` refers to ?

The `stable` is not SemVer compliant and to be honest is confusing as it's not clear what version from GitHub release is going to install.

### Configuration

Just trying to update to the latest using Helm charts.

### Fluent Bit Log Output 

N/A

### Fluent Bit Version Info

Helm chart version ` 0.1.26`

###  Cluster Details

N/A

### Application Details

N/A

### Steps to reproduce issue

```bash
helm repo add eks https://aws.github.io/eks-charts
$ helm repo update
$ helm search repo eks/aws-for-fluent-bit -l
NAME                  	CHART VERSION	APP VERSION	DESCRIPTION
eks/aws-for-fluent-bit	0.1.26       	stable     	A Helm chart to deploy aws-for-fluent-bit project
eks/aws-for-fluent-bit	0.1.25       	2.28.4     	A Helm chart to deploy aws-for-fluent-bit project
eks/aws-for-fluent-bit	0.1.24       	2.28.4     	A Helm chart to deploy aws-for-fluent-bit project
eks/aws-for-fluent-bit	0.1.23       	2.21.5     	A Helm chart to deploy aws-for-fluent-bit project
...
```

**Comment by PettitWesley** [comment]
https://github.com/aws/aws-for-fluent-bit/blob/mainline/troubleshooting/debugging.md#which-version-did-i-deploy

We're considering ways to update the helm chart to have the version tag of our stable version without the actual stable tag. https://github.com/aws/aws-for-fluent-bit/blob/mainline/AWS_FOR_FLUENT_BIT_STABLE_VERSION

**Comment by PettitWesley** [comment]
New chart version: https://github.com/aws/eks-charts/releases/tag/v0.0.140

**Comment by PettitWesley** [comment]
I've added a note to try to remember to upgrade the chart image tag every time we upgrade stable. Resolving this issue.

**Comment by Constantin07** [comment]
Much appreciated @PettitWesley.

I confirm it does report the version properly now:
```
$ helm search repo aws-for-fluent-bit
NAME                  	CHART VERSION	APP VERSION	DESCRIPTION
eks/aws-for-fluent-bit	0.1.27       	2.31.11    	A Helm chart to deploy aws-for-fluent-bit project
```
