### ISSUE TITLE
Use wildcard value for Output log_stream_name?

### ISSUE THREAD

**Issue by Derison** [aws/aws-for-fluent-bit#727]
Version: `amazon/aws-for-fluent-bit:stable`
Plugins: `cloudwatch` and `tail`

### Describe the question/issue
I want to make my fluent bit-config as generic as possible, so that I don't need to configure each log file separately. So I tried using wildcard for each input and output. Which looks like this:

```conf
[INPUT]
    Name tail
    Tag *-log
    Path /var/log/*.log
    DB /var/log/flb_service.db
    DB.locking true
    Skip_Long_Lines On
    Refresh_Interval 10
    Rotate_Wait 30

[OUTPUT]
    Name cloudwatch
    Match *-log
    region eu-central-1
    log_group_name /aws/$(ecs_cluster)
    log_stream_name /php/*/$(ecs_task_id)
    auto_create_group true
    retry_limit 2
```

My folder structure looks like this:
```
.
└── var/
    └── log/
        ├── database.log
        └── something.log
```

I expect log stream names like this:
`/php/database/{TASK_ID}`
`/php/something/{TASK_ID}`

But I am getting only this one:
`/php/./{TASK_ID}`

Is it possiblet to achieve what I want?

**Comment by PettitWesley** [comment]
>     log_stream_name /php/*/$(ecs_task_id)


I think there are multiple misunderstandings here, but one key one is that the `*` wildcard expansion only works in specific cases- in the match pattern and in the tail plugin tag. The `log_stream_name` does not support this.

Instead, you can try using `$(tag)` as shown here: https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit#templating-log-group-and-stream-names


I want to also this link as an interesting reference: https://github.com/aws/aws-for-fluent-bit/tree/mainline/use_cases/k8s-metadata-customize-cw

Let me know if that gets you want you want or if more help is needed.

**Comment by Derison** [comment]
Yes, I definitely misunderstood that. I was thinking way too simple. But I came up with a solution which works for me:

```
[INPUT]
    Name tail
    Tag *-log
    Path /var/log/*.log
    Path_Key path

[FILTER]
    Name rewrite_tag
    Match *-log
    Rule $path ^\/(.+\/(.+)).log$ php/$2 false
    Emitter_Name  re_emitted

[OUTPUT]
    Name cloudwatch
    Match php/*
    log_group_name /aws/$(ecs_cluster)
    log_stream_name /$(tag)
```

Thank you for the tip with `$(tag)`, that gave me the idea. I am closing this issue. 😄
