### ISSUE TITLE
Support for kube-events

### ISSUE THREAD

**Issue by daljitsharma** [aws/aws-for-fluent-bit#773]
### Describe the question/issue
I see fluentbit has a [Kubernetes Events](https://docs.fluentbit.io/manual/pipeline/inputs/kubernetes-events) input that ingest kube-events. Wondering if this input will be supported in aws-fluent-bit out of the box? We are currently using the [aws-fluent-bit](https://github.com/aws/eks-charts/tree/master/stable/aws-for-fluent-bit) chart to deploy to eks and forward logs to OpenSearch. And forwarding events will be very helpful

**Comment by weijianz-opc** [comment]
could you using this https://github.com/aws/aws-for-fluent-bit/issues/494 to track this. Thank you.
