### ISSUE TITLE
when can we fix the CVEs in the current stable version: 2.32.0.20240122

### ISSUE THREAD

**Issue by jenkoon** [aws/aws-for-fluent-bit#787]
![image](https://github.com/aws/aws-for-fluent-bit/assets/27683687/237b0285-ac85-4462-866c-8a4746d1a795)

**Comment by bendu** [comment]
Hi @weiZhenkun 

We have [released](https://github.com/aws/aws-for-fluent-bit/releases) rebuilds of AWS for Fluent Bit which are built off the AL2 base image released in late March. We are working on publishing an updated rebuild based on a more recent AL2 base image. (See our commit history on the mainline branch for the latest activity)
