### ISSUE TITLE
Issue sending logs to loki 'https'

### ISSUE THREAD

**Issue by hhertoghe** [aws/aws-for-fluent-bit#802]
Hello,

I'm trying to send logs from an AWS Fluent Bit docker to a Loki server exposed through caddy as reverse proxy.
When watching logs of the Fluent Bit container in cloudwatch, I see the following output:

....:443, HTTP status=400 Not retrying.
Client sent an HTTP request to an HTTPS server.

Any idea what could be the issue ? How can I force the image to use https ? I've setup the port to 443 but this seems the only way to do it.

Tx

**Comment by sparrc** [comment]
You might want to raise this issue with fluent-bit itself, but just looking at their docs there does appear to be a "tls" config option for the loki output, so you mght try that: https://docs.fluentbit.io/manual/pipeline/outputs/loki#configuration-parameters
