### ISSUE TITLE
Some logs are not created in Cloudwatch with version 2.8.0

### ISSUE THREAD

**Issue by caldo-pys** [aws/aws-for-fluent-bit#81]
Hi,
I have been using aws-for-fluent-bit:latest in production since few months with no issue, with redirection of logs to cloudwatch.
Since few days, it seems like some logs are not written anymore in Cloudwatch.
I went back to aws-for-fluent-bit:2.7.0 and it works perfectly.
I tried with aws-for-fluent-bit:2.8.0 and I am experiencing the issue

Here is the log of 2.7.0 version:

>  | 2020-10-14T17:18:25.438+04:00 | AWS for Fluent Bit Container Image Version 2.7.0
>   | 2020-10-14T17:18:25.483+04:00 | [1mFluent Bit v1.5.6[0m
>   | 2020-10-14T17:18:25.483+04:00 | * [1m[93mCopyright (C) 2019-2020 The Fluent Bit Authors[0m
>   | 2020-10-14T17:18:25.483+04:00 | * [1m[93mCopyright (C) 2015-2018 Treasure Data[0m
>   | 2020-10-14T17:18:25.483+04:00 | * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
>   | 2020-10-14T17:18:25.483+04:00 | * https://fluentbit.io
>   | 2020-10-14T17:18:25.484+04:00 | time="2020-10-14T13:18:25Z" level=info msg="[cloudwatch 0] plugin parameter log_group = <log_group>"
>   | 2020-10-14T17:18:25.484+04:00 | time="2020-10-14T13:18:25Z" level=info msg="[cloudwatch 0] plugin parameter log_stream_prefix = 'echo hello/'"
>   | 2020-10-14T17:18:25.484+04:00 | time="2020-10-14T13:18:25Z" level=info msg="[cloudwatch 0] plugin parameter log_stream_name = ''"
>   | 2020-10-14T17:18:25.485+04:00 | time="2020-10-14T13:18:25Z" level=info msg="[cloudwatch 0] plugin parameter region = 'eu-central-1'"
>   | 2020-10-14T17:18:25.485+04:00 | time="2020-10-14T13:18:25Z" level=info msg="[cloudwatch 0] plugin parameter log_key = 'log'"
>   | 2020-10-14T17:18:25.485+04:00 | time="2020-10-14T13:18:25Z" level=info msg="[cloudwatch 0] plugin parameter role_arn = ''"
>   | 2020-10-14T17:18:25.485+04:00 | time="2020-10-14T13:18:25Z" level=info msg="[cloudwatch 0] plugin parameter new_log_group_tags = ''"
>   | 2020-10-14T17:18:25.485+04:00 | time="2020-10-14T13:18:25Z" level=info msg="[cloudwatch 0] plugin parameter log_retention_days = '0'"
>   | 2020-10-14T17:18:25.485+04:00 | time="2020-10-14T13:18:25Z" level=info msg="[cloudwatch 0] plugin parameter endpoint = ''"
>   | 2020-10-14T17:18:25.485+04:00 | time="2020-10-14T13:18:25Z" level=info msg="[cloudwatch 0] plugin parameter sts_endpoint = ''"
>   | 2020-10-14T17:18:25.485+04:00 | time="2020-10-14T13:18:25Z" level=info msg="[cloudwatch 0] plugin parameter credentials_endpoint = "
>   | 2020-10-14T17:18:25.485+04:00 | time="2020-10-14T13:18:25Z" level=info msg="[cloudwatch 0] plugin parameter log_format = ''"
>   | 2020-10-14T17:18:25.485+04:00 | [2020/10/14 13:18:25] [ info] [engine] started (pid=1)
>   | 2020-10-14T17:18:25.486+04:00 | [2020/10/14 13:18:25] [ info] [storage] version=1.0.5, initializing...
>   | 2020-10-14T17:18:25.486+04:00 | [2020/10/14 13:18:25] [ info] [storage] in-memory
>   | 2020-10-14T17:18:25.486+04:00 | [2020/10/14 13:18:25] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
>   | 2020-10-14T17:18:25.486+04:00 | [2020/10/14 13:18:25] [ info] [input:forward:forward.0] listening on unix:///var/run/fluent.sock
>   | 2020-10-14T17:18:25.486+04:00 | [2020/10/14 13:18:25] [ info] [input:forward:forward.1] listening on 0.0.0.0:24224
>   | 2020-10-14T17:18:25.486+04:00 | [2020/10/14 13:18:25] [ info] [input:tcp:tcp.2] listening on 127.0.0.1:8877
>   | 2020-10-14T17:18:25.486+04:00 | [2020/10/14 13:18:25] [ info] [sp] stream processor started
>   | 2020-10-14T17:18:26.239+04:00 | [engine] caught signal (SIGTERM)
>   | 2020-10-14T17:18:26.301+04:00 | time="2020-10-14T13:18:26Z" level=info msg="[cloudwatch 0] Log group <log_group> exists\n"
>   | 2020-10-14T17:18:26.338+04:00 | time="2020-10-14T13:18:26Z" level=info msg="[cloudwatch 0] Created log stream echo hello/utils-firelens-<id> in group <log_group>"
>   | 2020-10-14T17:18:26.354+04:00 | [2020/10/14 13:18:26] [ warn] [engine] service will stop in 5 seconds
>   | 2020-10-14T17:18:30.913+04:00 | [2020/10/14 13:18:30] [ info] [engine] service stopped

Here is the log of 2.8.0 version:

> 2020-10-14T17:20:51.085+04:00 | AWS for Fluent Bit Container Image Version 2.8.0
>   | 2020-10-14T17:20:51.133+04:00 | [1mFluent Bit v1.6.0[0m
>   | 2020-10-14T17:20:51.133+04:00 | * [1m[93mCopyright (C) 2019-2020 The Fluent Bit Authors[0m
>   | 2020-10-14T17:20:51.133+04:00 | * [1m[93mCopyright (C) 2015-2018 Treasure Data[0m
>   | 2020-10-14T17:20:51.133+04:00 | * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
>   | 2020-10-14T17:20:51.133+04:00 | * https://fluentbit.io
>   | 2020-10-14T17:20:51.135+04:00 | [2020/10/14 13:20:51] [ info] [engine] started (pid=1)
>   | 2020-10-14T17:20:51.135+04:00 | [2020/10/14 13:20:51] [ info] [storage] version=1.0.6, initializing...
>   | 2020-10-14T17:20:51.135+04:00 | [2020/10/14 13:20:51] [ info] [storage] in-memory
>   | 2020-10-14T17:20:51.135+04:00 | [2020/10/14 13:20:51] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
>   | 2020-10-14T17:20:51.135+04:00 | [2020/10/14 13:20:51] [ info] [input:forward:forward.0] listening on unix:///var/run/fluent.sock
>   | 2020-10-14T17:20:51.135+04:00 | [2020/10/14 13:20:51] [ info] [input:forward:forward.1] listening on 0.0.0.0:24224
>   | 2020-10-14T17:20:51.135+04:00 | [2020/10/14 13:20:51] [ info] [input:tcp:tcp.2] listening on 127.0.0.1:8877
>   | 2020-10-14T17:20:51.135+04:00 | [2020/10/14 13:20:51] [ info] [sp] stream processor started
>   | 2020-10-14T17:20:51.135+04:00 | time="2020-10-14T13:20:51Z" level=info msg="[cloudwatch 0] plugin parameter log_group = <log_group>"
>   | 2020-10-14T17:20:51.135+04:00 | time="2020-10-14T13:20:51Z" level=info msg="[cloudwatch 0] plugin parameter log_stream_prefix = 'echo hello/'"
>   | 2020-10-14T17:20:51.135+04:00 | time="2020-10-14T13:20:51Z" level=info msg="[cloudwatch 0] plugin parameter log_stream_name = ''"
>   | 2020-10-14T17:20:51.135+04:00 | time="2020-10-14T13:20:51Z" level=info msg="[cloudwatch 0] plugin parameter region = 'eu-central-1'"
>   | 2020-10-14T17:20:51.135+04:00 | time="2020-10-14T13:20:51Z" level=info msg="[cloudwatch 0] plugin parameter log_key = 'log'"
>   | 2020-10-14T17:20:51.135+04:00 | time="2020-10-14T13:20:51Z" level=info msg="[cloudwatch 0] plugin parameter role_arn = ''"
>   | 2020-10-14T17:20:51.135+04:00 | time="2020-10-14T13:20:51Z" level=info msg="[cloudwatch 0] plugin parameter auto_create_group = 'false'"
>   | 2020-10-14T17:20:51.135+04:00 | time="2020-10-14T13:20:51Z" level=info msg="[cloudwatch 0] plugin parameter new_log_group_tags = ''"
>   | 2020-10-14T17:20:51.135+04:00 | time="2020-10-14T13:20:51Z" level=info msg="[cloudwatch 0] plugin parameter log_retention_days = '0'"
>   | 2020-10-14T17:20:51.135+04:00 | time="2020-10-14T13:20:51Z" level=info msg="[cloudwatch 0] plugin parameter endpoint = ''"
>   | 2020-10-14T17:20:51.135+04:00 | time="2020-10-14T13:20:51Z" level=info msg="[cloudwatch 0] plugin parameter sts_endpoint = ''"
>   | 2020-10-14T17:20:51.135+04:00 | time="2020-10-14T13:20:51Z" level=info msg="[cloudwatch 0] plugin parameter credentials_endpoint = "
>   | 2020-10-14T17:20:51.135+04:00 | time="2020-10-14T13:20:51Z" level=info msg="[cloudwatch 0] plugin parameter log_format = ''"
>   | 2020-10-14T17:20:52.157+04:00 | [2020/10/14 13:20:52] [engine] caught signal (SIGTERM)
>   | 2020-10-14T17:20:52.157+04:00 | [2020/10/14 13:20:52] [ info] [input] pausing forward.0
>   | 2020-10-14T17:20:52.157+04:00 | [2020/10/14 13:20:52] [ info] [input] pausing forward.1

**Comment by hossain-rayhan** [comment]
Hi @caldo-pys , if the scenario is partial log lost, do you see any specific pattern? Also, can you share your fluent-bit config file so that we can try to reproduce it.

**Comment by caldo-pys** [comment]
Hi @hossain-rayhan I don't use a specific fluent-bit config file, the configuration is directly in my task-definition.

Here is the interesting part in my task-definition :

`{
  "containerDefinitions": [
    {
      "essential": true,
      "image": "906394416424.dkr.ecr.eu-central-1.amazonaws.com/aws-for-fluent-bit:latest",
      "name": "log_router",
      "firelensConfiguration": {
        "type": "fluentbit"
      },
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "<awslogs-group>",
          "awslogs-region": "<region>",
          "awslogs-stream-prefix": "log_router"
        }
      },
      "environment": [
        {
          "name": "LOG_PREFIX",
          "value": "ecs"
        }
      ]
    },
    {
      "logConfiguration": {
        "logDriver": "awsfirelens",
        "options": {
          "Name": "cloudwatch",
          "region": "<region>",
          "log_group_name": "<log_group_name>",
          "log_stream_prefix": "${LOG_PREFIX}/",
          "log_key": "log"
        }
      },
      ...
    }
  ]
}
`

I then run a task with containerOverride on LOG_PREFIX environment variable

**Comment by andyklaiber** [comment]
We are seeing a similar problem with shipping to datadog.  we were using the latest tag, and noticed one of our tasks wasn't showing any log data.  hardcoding to 2.7.0 makes the log data come back.
logdriver config:
`LogConfiguration:
            LogDriver: awsfirelens
            Options:
              Name: datadog
              Host: "http-intake.logs.datadoghq.com"
              dd_service: v-db-util
              dd_source: nodejs
              dd_message_key: log
              dd_tags: !Sub "project:fluentbit,source:nodejs,service:v-db-util,env:${EnvironmentName},version:${DbUtilVersion}"
              TLS: "on"
              provider: ecs`
image config from our task definition:
`- Name: log-router
          Image: !Sub 906394416424.dkr.ecr.${AWS::Region}.amazonaws.com/aws-for-fluent-bit:latest
          Essential: true
          MemoryReservation: 256
          FirelensConfiguration:
            Type: fluentbit
            Options:
              enable-ecs-log-metadata: "true"
              config-file-type: file
              config-file-value: /fluent-bit/configs/parse-json.conf`

**Comment by gbleu** [comment]
Logs right before container shutdown are lost, downgrading to 2.7.0 fix the problem.

**Comment by PettitWesley** [comment]
There were some code changes to the shut down behavior of fluent bit in the latest release... looking into this... might be a bug..

**Comment by andyklaiber** [comment]
> Logs right before container shutdown are lost, downgrading to 2.7.0 fix the problem.

we didn't test thoroughly, but our missing logs were at the end of a task or part of a very short running task, so that sounds consistent with what we saw.

**Comment by PettitWesley** [comment]
This is an upstream bug. I've engaged the lead maintainer who recently made some changes to the shutdown code.

**Comment by aric49** [comment]
Seeing a similar issue as well since 2.8.0 was released, logging data into Sumo Logic.  Reverting the aws-for-fluent-bit container version back to 2.7.0 resolves the problem for me.

**Comment by PettitWesley** [comment]
This has been fixed
