### ISSUE TITLE
"No matching route" warning for rewritten tags in 1.6.0

### ISSUE THREAD

**Issue by LucasHantz** [aws/aws-for-fluent-bit#84]
Issue was raised and fixed on Fluenbit for the 1.6.0 release which is flooding my logs.
https://github.com/fluent/fluent-bit/issues/2684

Please consider updating Firelens image as soon as 1.6.1 is release.

**Comment by hossain-rayhan** [comment]
Hi @LucasHantz thanks for reporting this. We will plan a release once fluent-bit 1.6.1 is released and tested.

**Comment by SachinBadgujar** [comment]
Same issue here. What is the timeline for the new image release?

**Comment by PettitWesley** [comment]
Some time in the next week

**Comment by zhonghui12** [comment]
We have upgraded to Fluent Bit 1.6.3 for recent release. Please check more details here: https://github.com/aws/aws-for-fluent-bit/blob/mainline/CHANGELOG.md.

This issue will be closed. Thanks.
