### ISSUE TITLE
Request for specify or any method to change Fluent-bit  counter and flowcounter plugin output

### ISSUE THREAD

**Issue by totten25** [aws/aws-for-fluent-bit#85]
Hi all, 

I've used https://docs.fluentbit.io/manual/pipeline/outputs/counter and https://docs.fluentbit.io/manual/pipeline/outputs/flowcounter to get data statistics as format below 
// counter output
1603087116.245969,17 (total = 17)
// flow counter output
[out_flowcounter] [1603087136, {"counts":50, "bytes":66015, "counts/minute":0, "bytes/minute":1100 }]  

It does not compatible with Cloudwatch metric filter pattern that it uses space delimiter because I want to extract only 17 as single values or single columns. Are you able to format it to only json format or add space bar like apache logs

**Comment by PettitWesley** [comment]
The flow counter works right since its output is json? Can you just use that?
