### ISSUE TITLE
Indentation issue in extra.conf with s3_key_format with fargate service

### ISSUE THREAD

**Issue by anshul0915** [aws/aws-for-fluent-bit#86]
I am facing issue when i define s3_key_format in extra.conf getting  error 

[OUTPUT]
     Name s3
     Match *
     bucket	${LOG_BUCKET}
     region	${AWS_REGION}
     total_file_size 100M
     upload_timeout	1m
     s3_key_format /dev-env/$TAG/%Y/%m/%d/%H/%M/%S

![image](https://user-images.githubusercontent.com/7870013/96607957-7ea6c900-1316-11eb-8410-8f065c6f2825.png)

**Comment by PettitWesley** [comment]
Can you reproduce it locally outside of FireLens?

All keys must be indented at the same level in your config file

**Comment by zhonghui12** [comment]
This issue will be closed. Please re-open it for follow up questions.

Thanks.
