### ISSUE TITLE
Unexpected behaviour when using config with many [OUTPUT] sections

### ISSUE THREAD

**Issue by fdansey-ostmodern** [aws/aws-for-fluent-bit#88]
Howdy,
Running the latest image tag, `d043d7e505fa`, I get unexpected behaviour with my config file which has 45 `[OUTPUT]` sections.

I am using the '[cloudwatch](https://docs.fluentbit.io/manual/pipeline/outputs/cloudwatch)' output plugin to ship logs to separate log groups in AWS CloudWatch.
For some logs, the events are shipped to the _wrong_ log group as well as the correct one.  This snippet shows two examples:
```
time="2020-10-23T12:38:18Z" level=info msg="[cloudwatch 9] Created log stream fluentbit-kube.var.log.containers.camel-schedule-watcher-1603456680-zzf4n_camel_snapshotter-a1e5b58882df724794ba7097b68757cf3c759fd995416a3f60391918af207289.log in group /mycompany/camel/bearpig-internal-eks/application/external-dns"
time="2020-10-23T12:38:18Z" level=info msg="[cloudwatch 42] Created log stream fluentbit-kube.var.log.containers.camel-schedule-watcher-1603456680-zzf4n_camel_snapshotter-a1e5b58882df724794ba7097b68757cf3c759fd995416a3f60391918af207289.log in group /mycompany/camel/bearpig-internal-eks/application/camel-schedule-watcher"
time="2020-10-23T12:38:18Z" level=info msg="[cloudwatch 5] Created log stream fluentbit-kube.var.log.containers.camel-epg-watcher-1603456680-dmp8p_camel_snapshotter-7b7145575dad03dcb1e1ef0ed0e35cea30413b0d55883cd990a3fc00c0c4899f.log in group /mycompany/camel/bearpig-internal-eks/application/argocd-redis"
time="2020-10-23T12:38:18Z" level=info msg="[cloudwatch 38] Created log stream fluentbit-kube.var.log.containers.camel-epg-watcher-1603456680-dmp8p_camel_snapshotter-7b7145575dad03dcb1e1ef0ed0e35cea30413b0d55883cd990a3fc00c0c4899f.log in group /mycompany/camel/bearpig-internal-eks/application/camel-epg-watcher"
```
(The log event appears to trigger an additional output for which the tag does not match)
I only see this behaviour when the second line shows `[cloudwatch <n>]` where n > 32.
Is there a maximum number of `[OUTPUT]` sections of 32?

**Comment by PettitWesley** [comment]
@fdansey-ostmodern Interesting... also apologies for missing this issue.

32 is a nice number... a power of 2... looking through the core fluent bit code though, I can't see any clear reason why there would be a limit on the number of output instances. It's possible though. Sorry, I do not maintain that part of the code.

To me, it also seems rather possible that with 42 outputs you might have setup one of your match rules wrong...

Anyway, I think that you should check out the log group and stream name templating features of the Golang CloudWatch plugin. The golang plugin isn't as efficient, and with it Fluent Bit won't be able to scale as well, but it might allow you to condense your output definitions. 

https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit

I see you are using kubernetes- what is your approximate log generation rate per node? The Fluent Bit go plugins can handle a couple thousand logs per second, if the logs are small. If you produce logs more quickly then you do need the core/high performance output.

**Comment by PettitWesley** [comment]
The question of the max number of output sections is worth asking to the core maintainers on the upstream fluent/fluent-bit repo

**Comment by nokute78** [comment]
32+ outputs bug is fixed https://github.com/fluent/fluent-bit/pull/2882 and the patch is released from fluent-bit v1.7.0.

**Comment by PettitWesley** [comment]
@nokute78 So we can close this issue?

**Comment by PettitWesley** [comment]
@nokute78 Thanks!
