### ISSUE TITLE
Upgrade to Fluent-bit 1.6.2 - Fix ElasticSearch

### ISSUE THREAD

**Issue by allamand** [aws/aws-for-fluent-bit#90]
See : https://fluentbit.io/announcements/v1.6.2/
I'm interested on the Fix regarding ElasticSearch

**Comment by PettitWesley** [comment]
We will do a release some time this week

**Comment by allamand** [comment]
Thanks @PettitWesley

**Comment by zhonghui12** [comment]
Hi @allamand, we have upgraded to Fluent-bit 1.6.3 for recent release. Please check more details here: https://github.com/aws/aws-for-fluent-bit/blob/mainline/CHANGELOG.md.

Will close this issue. Thanks.
